// This file was auto-generated by the veyron vdl tool.
// Source: stats.vdl

/**
 * Package stats defines an interface to access statistical information for
 * troubleshooting and monitoring purposes.
 */

package com.veyron2.services.mgmt.stats;
