// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl

/**
 * Package types contains the types used by the logreader interface.
 */

package com.veyron2.services.mgmt.logreader.types;
