// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.store;

/**
 * Statable provides the Stat method.
 */

@com.veyron2.vdl.VeyronService(serviceWrapper=com.veyron2.services.store.gen_impl.StatableServiceWrapper.class)
public interface StatableService  {

    
    // Stat returns information about the receiver.

    public com.veyron2.storage.Stat stat(final com.veyron2.ipc.ServerContext context) throws com.veyron2.ipc.VeyronException;

}
