// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.store;


@com.veyron2.vdl.VeyronService(serviceWrapper=com.veyron2.services.store.gen_impl.TransactionRootServiceWrapper.class)
public interface TransactionRootService  {

    
    // CreateTransaction creates a transaction with the given options.  It returns
// the name of the transaction relative to this TransactionRoot's name.

    public java.lang.String createTransaction(final com.veyron2.ipc.ServerContext context, final java.util.ArrayList<java.lang.Object> Options) throws com.veyron2.ipc.VeyronException;

}
