// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.store;


@com.veyron2.vdl.VeyronService(serviceWrapper=com.veyron2.services.store.gen_impl.TransactionServiceWrapper.class)
public interface TransactionService  {

    
    // Commit commits the changes in the transaction to the store.  The
// operation is atomic, so all mutations are performed, or none.  Returns an
// error if the transaction aborted.

    public void commit(final com.veyron2.ipc.ServerContext context) throws com.veyron2.ipc.VeyronException;

    
    // Abort discards a transaction.  This is an optimization; transactions
// eventually time out and get discarded.  However, live transactions
// consume resources, so if you know that you won't be using a transaction
// anymore, you should discard it explicitly.

    public void abort(final com.veyron2.ipc.ServerContext context) throws com.veyron2.ipc.VeyronException;

}
