// This file was auto-generated by the veyron vdl tool.
// Source(s): application.vdl
package com.veyron2.services.mgmt.application;


public class VeyronConsts { 
	/* The following constants originate in file: application.vdl. */
	// Node manager application envelopes must present this title.
	public static final String NODE_MANAGER_TITLE = "node manager";
}
