// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.watch;

/**
 * type ChangeBatch struct{Changes []veyron2/services/watch.Change struct{Name string;State int32;Value any;ResumeMarker veyron2/services/watch.ResumeMarker []byte;Continued bool}} 
 * ChangeBatch is a batch of Change messages.
 **/
public final class ChangeBatch {
    
    
      private java.util.ArrayList<com.veyron2.services.watch.Change> changes;
    

    
    public ChangeBatch(final java.util.ArrayList<com.veyron2.services.watch.Change> changes) {
        
            this.changes = changes;
        
    }

    
    
    public java.util.ArrayList<com.veyron2.services.watch.Change> getChanges() {
        return this.changes;
    }
    public void setChanges(java.util.ArrayList<com.veyron2.services.watch.Change> changes) {
        this.changes = changes;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final ChangeBatch other = (ChangeBatch)obj;

        
        
        if (this.changes == null) {
            if (other.changes != null) {
                return false;
            }
        } else if (!this.changes.equals(other.changes)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (changes == null ? 0 : changes.hashCode());
        
        return result;
    }
}