// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package io.veyron.examples.todos.schema;

/**
 * type List struct{Name string} 
 * List is a list of items.
 **/
public final class List implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      @com.google.gson.annotations.SerializedName("Name")
      private java.lang.String name;
    

    
    public List(final java.lang.String name) {
        
            this.name = name;
        
    }

    
    
    public java.lang.String getName() {
        return this.name;
    }
    public void setName(java.lang.String name) {
        this.name = name;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final List other = (List)obj;

        
        
        
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (name == null ? 0 : name.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, name);
    	
    }
	public static final android.os.Parcelable.Creator<List> CREATOR
		= new android.os.Parcelable.Creator<List>() {
		@Override
		public List createFromParcel(android.os.Parcel in) {
			return new List(in);
		}
		@Override
		public List[] newArray(int size) {
			return new List[size];
		}
	};
	private List(android.os.Parcel in) {
		
			this.name = (java.lang.String) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.name);
		
	}
}