// This file was auto-generated by the veyron vdl tool.
// Source: proximity.vdl
package com.veyron2.services.proximity.vdlgen;

import com.veyron2.ipc.ServerContext;
import com.veyron2.ipc.VeyronException;
import java.util.ArrayList;

public interface ProximityScannerService { 
	// NearbyDevices returns the most up-to-date list of nearby devices,
// sorted in increasing distance order.
	public ArrayList<Device> nearbyDevices(ServerContext context) throws VeyronException;
}
