// This file was auto-generated by the veyron vdl tool.
// Source: proximity.vdl
package com.veyron2.services.proximity.vdlgen;


public interface Proximity extends ProximityAnnouncer, ProximityScanner { 
}
