
// This file was auto-generated by the veyron vdl tool.
// Source: profile.vdl
package com.veyron.services.mgmt.profile.vdlgen;

import java.util.HashSet;

/**
 * Specification is how we represent a profile internally. It should
 * provide enough information to allow matching of binaries to nodes.
**/
public class Specification { 
	// Format is the file format of the application binary.
public Format format;
	// Libraries is a set of libraries the application binary depends on.
public HashSet<Library> libraries;
	// A human-friendly concise label for the profile, e.g. "linux-media"
public String label;
	// A human-friendly description of the profile.
public String description;
}
