// This file was auto-generated by the veyron vdl tool.
// Source(s):  protocol.vdl
package com.veyron.runtimes.google.ipc.stream.proxy.vdlgen;

import com.google.common.reflect.TypeToken;
import com.veyron2.OptionDefs;
import com.veyron2.Options;
import com.veyron2.RuntimeFactory;

public class Client { 
	/* Bind methods for interfaces in file: protocol.vdl. */

	/* Client stubs for interfaces in file: protocol.vdl. */
}
