// This file was auto-generated by the veyron vdl tool.
// Source(s):  repository.vdl
package com.veyron2.services.mgmt.repository.gen_impl;

public final class BinaryServiceWrapper {

    private final com.veyron2.services.mgmt.repository.BinaryService service;




    public BinaryServiceWrapper(final com.veyron2.services.mgmt.repository.BinaryService service) {
        this.service = service;
        
        
    }

    /**
     * Returns all tags associated with the provided method or null if the method isn't implemented
     * by this service.
     */
    public java.lang.Object[] getMethodTags(final com.veyron2.ipc.ServerCall call, final java.lang.String method) throws com.veyron2.ipc.VeyronException {
        
        if ("create".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(2), 
            };
        }
        
        if ("delete".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(2), 
            };
        }
        
        if ("download".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(1), 
            };
        }
        
        if ("downloadURL".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(1), 
            };
        }
        
        if ("getMethodTags".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("stat".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(1), 
            };
        }
        
        if ("upload".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(2), 
            };
        }
        
        
        throw new com.veyron2.ipc.VeyronException("method: " + method + " not found");
    }

     
    
    public void create(final com.veyron2.ipc.ServerCall call, final int nparts) throws com.veyron2.ipc.VeyronException {
         
         this.service.create( call , nparts  );
    }

    public void delete(final com.veyron2.ipc.ServerCall call) throws com.veyron2.ipc.VeyronException {
         
         this.service.delete( call   );
    }

    public void download(final com.veyron2.ipc.ServerCall call, final int part) throws com.veyron2.ipc.VeyronException {
        
        final com.veyron2.vdl.Stream<java.lang.Void, java.util.ArrayList<java.lang.Byte>> stream = new com.veyron2.vdl.Stream<java.lang.Void, java.util.ArrayList<java.lang.Byte>>() {
            @Override
            public void send(java.lang.Void item) throws com.veyron2.ipc.VeyronException {
                call.send(item);
            }
            @Override
            public java.util.ArrayList<java.lang.Byte> recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
                final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken< java.util.ArrayList<java.lang.Byte> >() {
                    private static final long serialVersionUID = 1L;
                };
                final java.lang.Object result = call.recv(type);
                try {
                    return (java.util.ArrayList<java.lang.Byte>)result;
                } catch (java.lang.ClassCastException e) {
                    throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
                }
            }
        };
         
         this.service.download( call , part  ,stream  );
    }

    public com.veyron2.services.mgmt.repository.Binary.DownloadURLOut downloadURL(final com.veyron2.ipc.ServerCall call) throws com.veyron2.ipc.VeyronException {
         
         return  this.service.downloadURL( call   );
    }

    public java.util.ArrayList<com.veyron2.services.mgmt.binary.PartInfo> stat(final com.veyron2.ipc.ServerCall call) throws com.veyron2.ipc.VeyronException {
         
         return  this.service.stat( call   );
    }

    public void upload(final com.veyron2.ipc.ServerCall call, final int part) throws com.veyron2.ipc.VeyronException {
        
        final com.veyron2.vdl.Stream<java.util.ArrayList<java.lang.Byte>, java.lang.Void> stream = new com.veyron2.vdl.Stream<java.util.ArrayList<java.lang.Byte>, java.lang.Void>() {
            @Override
            public void send(java.util.ArrayList<java.lang.Byte> item) throws com.veyron2.ipc.VeyronException {
                call.send(item);
            }
            @Override
            public java.lang.Void recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
                final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken< java.lang.Void >() {
                    private static final long serialVersionUID = 1L;
                };
                final java.lang.Object result = call.recv(type);
                try {
                    return (java.lang.Void)result;
                } catch (java.lang.ClassCastException e) {
                    throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
                }
            }
        };
         
         this.service.upload( call , part  ,stream  );
    }



 

}
