// This file was auto-generated by the veyron vdl tool.
// Source(s):  repository.vdl
package com.veyron.services.mgmt.repository.gen_impl;

import com.veyron.services.mgmt.profile.Specification;
import com.veyron.services.mgmt.repository.Application;
import com.veyron.services.mgmt.repository.ApplicationFactory;
import com.veyron.services.mgmt.repository.ApplicationService;
import com.veyron.services.mgmt.repository.Profile;
import com.veyron.services.mgmt.repository.ProfileFactory;
import com.veyron.services.mgmt.repository.ProfileService;
import com.veyron2.ipc.ServerCall;
import com.veyron2.ipc.VeyronException;

public class ProfileServiceWrapper {

	private final ProfileService service;
	private final ProfileServiceWrapper profile;

	public ProfileServiceWrapper(ProfileService service) {
		this.profile = new ProfileServiceWrapper(service);
		this.service = service;
	}
	/**
	 * Returns all tags associated with the provided method or null if the method isn't implemented
	 * by this service.
	 */
	public Object[] getMethodTags(ServerCall call, String method) throws VeyronException { 
		try {
			return this.profile.getMethodTags(call, method);
		} catch (VeyronException e) {}  // method not found.
		if ("specification".equals(method)) {
			return new Object[]{ new com.veyron2.security.Label(1) };
		}
		if ("put".equals(method)) {
			return new Object[]{ new com.veyron2.security.Label(2) };
		}
		if ("remove".equals(method)) {
			return new Object[]{ new com.veyron2.security.Label(2) };
		}
        if ("getMethodTags".equals(method)) {
            return new Object[]{};
        }
		throw new VeyronException("method: " + method + " not found");
	}
	// Methods from interface Profile.
	public Specification specification(ServerCall call) throws VeyronException { 
		return this.service.specification(call);
	}
	public void put(ServerCall call, Specification Specification) throws VeyronException { 
		this.service.put(call, Specification);
	}
	public void remove(ServerCall call) throws VeyronException { 
		this.service.remove(call);
	}
	// Methods from sub-interface Profile.
	public String label(ServerCall call) throws VeyronException {
		return this.profile.label(call);
	}
	public String description(ServerCall call) throws VeyronException {
		return this.profile.description(call);
	}
}
