// This file was auto-generated by the veyron vdl tool.
// Source(s):  tunnel.vdl
package io.veyron.examples.tunnel.gen_impl;

public final class TunnelServiceWrapper {

    private final io.veyron.examples.tunnel.TunnelService service;




    public TunnelServiceWrapper(final io.veyron.examples.tunnel.TunnelService service) {
        this.service = service;
        
        
    }

    /**
     * Returns all tags associated with the provided method or null if the method isn't implemented
     * by this service.
     */
    public java.lang.Object[] getMethodTags(final com.veyron2.ipc.ServerCall call, final java.lang.String method) throws com.veyron2.ipc.VeyronException {
        
        if ("forward".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(8), 
            };
        }
        
        if ("getMethodTags".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("shell".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(8), 
            };
        }
        
        
        throw new com.veyron2.ipc.VeyronException("method: " + method + " not found");
    }

     
    
    public void forward(final com.veyron2.ipc.ServerCall call, final java.lang.String network, final java.lang.String address) throws com.veyron2.ipc.VeyronException {
        
        final com.veyron2.vdl.Stream<byte[], byte[]> stream = new com.veyron2.vdl.Stream<byte[], byte[]>() {
            @Override
            public void send(byte[] item) throws com.veyron2.ipc.VeyronException {
                call.send(item);
            }
            @Override
            public byte[] recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
                final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken< byte[] >() {
                    private static final long serialVersionUID = 1L;
                };
                final java.lang.Object result = call.recv(type);
                try {
                    return (byte[])result;
                } catch (java.lang.ClassCastException e) {
                    throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
                }
            }
        };
         
         this.service.forward( call , network, address  ,stream  );
    }

    public int shell(final com.veyron2.ipc.ServerCall call, final java.lang.String command, final io.veyron.examples.tunnel.ShellOpts shellOpts) throws com.veyron2.ipc.VeyronException {
        
        final com.veyron2.vdl.Stream<io.veyron.examples.tunnel.ClientShellPacket, io.veyron.examples.tunnel.ServerShellPacket> stream = new com.veyron2.vdl.Stream<io.veyron.examples.tunnel.ClientShellPacket, io.veyron.examples.tunnel.ServerShellPacket>() {
            @Override
            public void send(io.veyron.examples.tunnel.ClientShellPacket item) throws com.veyron2.ipc.VeyronException {
                call.send(item);
            }
            @Override
            public io.veyron.examples.tunnel.ServerShellPacket recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
                final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken< io.veyron.examples.tunnel.ServerShellPacket >() {
                    private static final long serialVersionUID = 1L;
                };
                final java.lang.Object result = call.recv(type);
                try {
                    return (io.veyron.examples.tunnel.ServerShellPacket)result;
                } catch (java.lang.ClassCastException e) {
                    throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
                }
            }
        };
         
         return  this.service.shell( call , command, shellOpts  ,stream  );
    }



 

}
