// This file was auto-generated by the veyron vdl tool.
// Source: vsync.vdl

package com.veyron.runtimes.google.vsync;

/**
 * type GenVector map[veyron/runtimes/google/vsync.DeviceID string]veyron/runtimes/google/vsync.GenID uint64 
 * GenVector is the generation vector.
 **/
public final class GenVector implements java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID>, android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    private java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID> impl;

    public GenVector(java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID> impl) {
        this.impl = impl;
    }

    public java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID> getValue() {
        return this.impl;
    }

    public void setValue(java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID> newImpl) {
        this.impl = newImpl;
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        final GenVector other = (GenVector) obj;
        if (!(this.impl.equals(other.impl)))
            return false;
        return true;
    }
    @Override
    public int hashCode() {
        return (impl == null) ? 0 : impl.hashCode();
    }

    @Override
    public void clear() {
        impl.clear();
    }
    @Override
    public boolean containsKey(java.lang.Object key) {
        return impl.containsKey(key);
    }
    @Override
    public boolean containsValue(java.lang.Object value) {
        return impl.containsValue(value);
    }
    @Override
    public java.util.Set<java.util.Map.Entry<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID>> entrySet() {
        return impl.entrySet();
    }
    @Override
    public com.veyron.runtimes.google.vsync.GenID get(java.lang.Object key) {
        return impl.get(key);
    }
    @Override
    public boolean isEmpty() {
        return impl.isEmpty();
    }
    @Override
    public java.util.Set<com.veyron.runtimes.google.vsync.DeviceID> keySet() {
        return impl.keySet();
    }
    @Override
    public com.veyron.runtimes.google.vsync.GenID put(com.veyron.runtimes.google.vsync.DeviceID key, com.veyron.runtimes.google.vsync.GenID value) {
        return impl.put(key, value);
    }
    @Override
    public void putAll(java.util.Map<? extends com.veyron.runtimes.google.vsync.DeviceID, ? extends com.veyron.runtimes.google.vsync.GenID> map) {
        impl.putAll(map);
    }
    @Override
    public com.veyron.runtimes.google.vsync.GenID remove(java.lang.Object key) {
        return impl.remove(key);
    }
    @Override
    public int size() {
        return impl.size();
    }
    @Override
    public java.util.Collection<com.veyron.runtimes.google.vsync.GenID> values() {
        return impl.values();
    }

    @Override
    public int describeContents() {
        return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        com.veyron2.vdl.ParcelUtil.writeValue(out, impl);
    }
    public static final android.os.Parcelable.Creator<GenVector> CREATOR = new android.os.Parcelable.Creator<GenVector>() {
        @Override
        public GenVector createFromParcel(android.os.Parcel in) {
            return new GenVector(in);
        }
        @Override
        public GenVector[] newArray(int size) {
            return new GenVector[size];
        }
    };
    private GenVector(android.os.Parcel in) {
        impl = (java.util.Map<com.veyron.runtimes.google.vsync.DeviceID, com.veyron.runtimes.google.vsync.GenID>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), impl);
    }
}
