// This file was auto-generated by the veyron vdl tool.
// Source: wire.vdl
package com.veyron2.security.wire;

/**
 * type PublicKey struct{Curve veyron2/security/wire.KeyCurve byte;XY []byte} 
 * PublicKey represents an ECDSA PublicKey.
 **/
public final class PublicKey {
    
    
      private com.veyron2.security.wire.KeyCurve curve;
    
      private java.util.ArrayList<java.lang.Byte> xY;
    

    
    public PublicKey(final com.veyron2.security.wire.KeyCurve curve, final java.util.ArrayList<java.lang.Byte> xY) {
        
            this.curve = curve;
        
            this.xY = xY;
        
    }

    
    
    public com.veyron2.security.wire.KeyCurve getCurve() {
        return this.curve;
    }
    public void setCurve(com.veyron2.security.wire.KeyCurve curve) {
        this.curve = curve;
    }
    
    public java.util.ArrayList<java.lang.Byte> getXY() {
        return this.xY;
    }
    public void setXY(java.util.ArrayList<java.lang.Byte> xY) {
        this.xY = xY;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final PublicKey other = (PublicKey)obj;

        
        
        if (this.curve == null) {
            if (other.curve != null) {
                return false;
            }
        } else if (!this.curve.equals(other.curve)) {
            return false;
        }
         
        
        
        if (this.xY == null) {
            if (other.xY != null) {
                return false;
            }
        } else if (!this.xY.equals(other.xY)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (curve == null ? 0 : curve.hashCode());
        
        result = prime * result + (xY == null ? 0 : xY.hashCode());
        
        return result;
    }
}