// This file was auto-generated by the veyron vdl tool.
// Source: wire.vdl
package com.veyron2.security.wire;

/**
 * type PublicKey struct{Curve veyron2/security/wire.KeyCurve byte;XY []byte} 
 * PublicKey represents an ECDSA PublicKey.
 **/
public final class PublicKey implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      private com.veyron2.security.wire.KeyCurve curve;
    
      private java.util.List<java.lang.Byte> xY;
    

    
    public PublicKey(final com.veyron2.security.wire.KeyCurve curve, final java.util.List<java.lang.Byte> xY) {
        
            this.curve = curve;
        
            this.xY = xY;
        
    }

    
    
    public com.veyron2.security.wire.KeyCurve getCurve() {
        return this.curve;
    }
    public void setCurve(com.veyron2.security.wire.KeyCurve curve) {
        this.curve = curve;
    }
    
    public java.util.List<java.lang.Byte> getXY() {
        return this.xY;
    }
    public void setXY(java.util.List<java.lang.Byte> xY) {
        this.xY = xY;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final PublicKey other = (PublicKey)obj;

        
        
        if (this.curve == null) {
            if (other.curve != null) {
                return false;
            }
        } else if (!this.curve.equals(other.curve)) {
            return false;
        }
         
        
        
        if (this.xY == null) {
            if (other.xY != null) {
                return false;
            }
        } else if (!this.xY.equals(other.xY)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (curve == null ? 0 : curve.hashCode());
        
        result = prime * result + (xY == null ? 0 : xY.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, curve);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, xY);
    	
    }
	public static final android.os.Parcelable.Creator<PublicKey> CREATOR
		= new android.os.Parcelable.Creator<PublicKey>() {
		@Override
		public PublicKey createFromParcel(android.os.Parcel in) {
			return new PublicKey(in);
		}
		@Override
		public PublicKey[] newArray(int size) {
			return new PublicKey[size];
		}
	};
	private PublicKey(android.os.Parcel in) {
		
			this.curve = (com.veyron2.security.wire.KeyCurve) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.curve);
		
			this.xY = (java.util.List<java.lang.Byte>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.xY);
		
	}
}