
// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package com.veyron.examples.todos.schema;


/**
 * List is a list of items.
 */
public final class List { 
		private String name;

	public List(String name) { 
		this.name = name;
	}
	public String getName() { return this.name; }

	public void setName(String name) { this.name = name; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final List other = (List)obj;
		if (!(this.name.equals(other.name))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (name == null ? 0 : name.hashCode());
		return result;
	}
}
