// This file was auto-generated by the veyron vdl tool.
// Source: syncgroup.vdl
package io.veyron.store.veyron.services.syncgroup;

/**
 * type JoinerMetaData struct{SyncPriority int32} 
 * A JoinerMetaData contains the non-name information stored per joiner.
 **/
public final class JoinerMetaData implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      @com.google.gson.annotations.SerializedName("SyncPriority")
      private int syncPriority;
    

    
    public JoinerMetaData(final int syncPriority) {
        
            this.syncPriority = syncPriority;
        
    }

    
    
    public int getSyncPriority() {
        return this.syncPriority;
    }
    public void setSyncPriority(int syncPriority) {
        this.syncPriority = syncPriority;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final JoinerMetaData other = (JoinerMetaData)obj;

        
        
        
        if (this.syncPriority != other.syncPriority) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + syncPriority;
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, syncPriority);
    	
    }
	public static final android.os.Parcelable.Creator<JoinerMetaData> CREATOR
		= new android.os.Parcelable.Creator<JoinerMetaData>() {
		@Override
		public JoinerMetaData createFromParcel(android.os.Parcel in) {
			return new JoinerMetaData(in);
		}
		@Override
		public JoinerMetaData[] newArray(int size) {
			return new JoinerMetaData[size];
		}
	};
	private JoinerMetaData(android.os.Parcel in) {
		
			this.syncPriority = (int) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.syncPriority);
		
	}
}