
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;


public final class NamedUint64 { 
		private long value;

	public NamedUint64(long value) { 
		this.value = value;
	}
	public long getValue() { return this.value; }

	public void setValue(long value) { this.value = value; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (!(obj instanceof NamedUint64)) return false;
		final NamedUint64 other = (NamedUint64)obj;
		if (this.value != other.value) return false;
		return true;
	}
}
