
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;

/**
 * type NamedByte byte 
 **/
public final class NamedByte {
    private byte value;

    public NamedByte(byte value) {
        this.value = value;
    }
    public byte getValue() { return this.value; }

    public void setValue(byte value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.vdl.test_base.NamedByte other = (com.veyron2.vdl.test_base.NamedByte)obj;
        
        return this.value == other.value;
        
    }
    @Override
    public int hashCode() {
        return (int)value;
    }
}
