
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;


/**
 *NamedEnum       enum{A;B;C}
**/
public final class NamedArray { 
		private boolean[] value;

	public NamedArray(boolean[] value) { 
		this.value = value;
	}
	public boolean[] getValue() { return this.value; }

	public void setValue(boolean[] value) { this.value = value; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (!(obj instanceof NamedArray)) return false;
		final NamedArray other = (NamedArray)obj;
		if (!(this.value.equals(other.value))) return false;
		return true;
	}
}
