// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;


public interface ServiceA  {

    
    

    
    
    public void methodA1(final com.veyron2.ipc.Context context) throws com.veyron2.ipc.VeyronException;
    public void methodA1(final com.veyron2.ipc.Context context, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

    
    

    
    
    public java.lang.String methodA2(final com.veyron2.ipc.Context context, final int a, final java.lang.String b) throws com.veyron2.ipc.VeyronException;
    public java.lang.String methodA2(final com.veyron2.ipc.Context context, final int a, final java.lang.String b, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

    
    

    
    
    public com.veyron2.vdl.ClientStream<java.lang.Void,com.veyron2.vdl.test_base.Scalars, java.lang.String> methodA3(final com.veyron2.ipc.Context context, final int a) throws com.veyron2.ipc.VeyronException;
    public com.veyron2.vdl.ClientStream<java.lang.Void,com.veyron2.vdl.test_base.Scalars, java.lang.String> methodA3(final com.veyron2.ipc.Context context, final int a, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

    
    

    
    
    public com.veyron2.vdl.ClientStream<java.lang.Integer,java.lang.String, java.lang.Void> methodA4(final com.veyron2.ipc.Context context, final int a) throws com.veyron2.ipc.VeyronException;
    public com.veyron2.vdl.ClientStream<java.lang.Integer,java.lang.String, java.lang.Void> methodA4(final com.veyron2.ipc.Context context, final int a, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

}
