// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package io.v.moments.ifc;

import io.v.moments.model.MomentIfcClient;

/**
 * Something that makes clients to Moment services.
 *
 * This interface should be generated by the Vanadium VDL generator, but isn't.
 * The generator only emits static functions.
 */
public interface MomentClientFactory {
    MomentIfcClient makeClient(String name);
}
