// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package com.veyron.examples.storage.mdb.schema;

/**
 * type Movie struct{Image string;Title string;Summary string;Language string;ReleaseDate int64;Runtime int64;Genre string;Director veyron2/storage.ID [16]byte} 
 * Movie represents a movie.
 **/
public final class Movie {
    
    
      private java.lang.String image;
    
      private java.lang.String title;
    
      private java.lang.String summary;
    
      private java.lang.String language;
    
      private long releaseDate;
    
      private long runtime;
    
      private java.lang.String genre;
    
      private com.veyron2.storage.ID director;
    

    
    public Movie(final java.lang.String image, final java.lang.String title, final java.lang.String summary, final java.lang.String language, final long releaseDate, final long runtime, final java.lang.String genre, final com.veyron2.storage.ID director) {
        
            this.image = image;
        
            this.title = title;
        
            this.summary = summary;
        
            this.language = language;
        
            this.releaseDate = releaseDate;
        
            this.runtime = runtime;
        
            this.genre = genre;
        
            this.director = director;
        
    }

    
    
    public java.lang.String getImage() {
        return this.image;
    }
    public void setImage(java.lang.String image) {
        this.image = image;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getSummary() {
        return this.summary;
    }
    public void setSummary(java.lang.String summary) {
        this.summary = summary;
    }
    
    public java.lang.String getLanguage() {
        return this.language;
    }
    public void setLanguage(java.lang.String language) {
        this.language = language;
    }
    
    public long getReleaseDate() {
        return this.releaseDate;
    }
    public void setReleaseDate(long releaseDate) {
        this.releaseDate = releaseDate;
    }
    
    public long getRuntime() {
        return this.runtime;
    }
    public void setRuntime(long runtime) {
        this.runtime = runtime;
    }
    
    public java.lang.String getGenre() {
        return this.genre;
    }
    public void setGenre(java.lang.String genre) {
        this.genre = genre;
    }
    
    public com.veyron2.storage.ID getDirector() {
        return this.director;
    }
    public void setDirector(com.veyron2.storage.ID director) {
        this.director = director;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final Movie other = (Movie)obj;

        
        
        if (this.image == null) {
            if (other.image != null) {
                return false;
            }
        } else if (!this.image.equals(other.image)) {
            return false;
        }
         
        
        
        if (this.title == null) {
            if (other.title != null) {
                return false;
            }
        } else if (!this.title.equals(other.title)) {
            return false;
        }
         
        
        
        if (this.summary == null) {
            if (other.summary != null) {
                return false;
            }
        } else if (!this.summary.equals(other.summary)) {
            return false;
        }
         
        
        
        if (this.language == null) {
            if (other.language != null) {
                return false;
            }
        } else if (!this.language.equals(other.language)) {
            return false;
        }
         
        
        
        if (this.releaseDate != other.releaseDate) {
            return false;
        }
         
        
        
        if (this.runtime != other.runtime) {
            return false;
        }
         
        
        
        if (this.genre == null) {
            if (other.genre != null) {
                return false;
            }
        } else if (!this.genre.equals(other.genre)) {
            return false;
        }
         
        
        
        if (this.director == null) {
            if (other.director != null) {
                return false;
            }
        } else if (!this.director.equals(other.director)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (image == null ? 0 : image.hashCode());
        
        result = prime * result + (title == null ? 0 : title.hashCode());
        
        result = prime * result + (summary == null ? 0 : summary.hashCode());
        
        result = prime * result + (language == null ? 0 : language.hashCode());
        
        result = prime * result + java.lang.Long.valueOf(releaseDate).hashCode();
        
        result = prime * result + java.lang.Long.valueOf(runtime).hashCode();
        
        result = prime * result + (genre == null ? 0 : genre.hashCode());
        
        result = prime * result + (director == null ? 0 : director.hashCode());
        
        return result;
    }
}