
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base.vdlgen;

import java.util.ArrayList;
import java.util.HashMap;
import org.apache.commons.math3.complex.Complex;

public class Composites { 
	public Scalars a0;
	public Scalars[] a1;
	public ArrayList<Scalars> a2;
	//A3 set[Scalars]
public HashMap<String, Scalars> a4;
	public HashMap<Scalars, ArrayList<HashMap<String, Complex>>> a5;
}
