// This file was auto-generated by the veyron vdl tool.
// Source(s):  boxes.vdl
package com.veyron.examples.boxes.vdlgen;

import com.google.common.reflect.TypeToken;
import com.veyron2.ipc.ServerCall;
import com.veyron2.ipc.VeyronException;
import com.veyron2.vdl.Stream;

public class Server { 
	/* Server stub creation methods for interfaces in file: boxes.vdl. */
	public static Object newBoxSignalling(BoxSignallingService service) { 
		return new BoxSignallingStub(service);
	}
	public static Object newDrawInterface(DrawInterfaceService service) { 
		return new DrawInterfaceStub(service);
	}
	
	/* Server stubs for interfaces in file: boxes.vdl. */
	public static class BoxSignallingStub {
		private final BoxSignallingService service;

		BoxSignallingStub(BoxSignallingService service) {
			this.service = service;
		}
		/**
		 * Returns all tags associated with the provided method or null if the method isn't implemented
		 * by this service.
		 */
		@SuppressWarnings("unused")
		public Object[] getMethodTags(ServerCall call, String method) { 
			if (method == "Add") {
				return new Object[]{  };
			}
			if (method == "Get") {
				return new Object[]{  };
			}
			return null;
		}
		// Methods from interface BoxSignalling.
		public void add(ServerCall call, String Endpoint) throws VeyronException { 
			this.service.add(call, Endpoint);
		}
		public String get(ServerCall call) throws VeyronException { 
			return this.service.get(call);
		}
	}
	public static class DrawInterfaceStub {
		private final DrawInterfaceService service;

		DrawInterfaceStub(DrawInterfaceService service) {
			this.service = service;
		}
		/**
		 * Returns all tags associated with the provided method or null if the method isn't implemented
		 * by this service.
		 */
		@SuppressWarnings("unused")
		public Object[] getMethodTags(ServerCall call, String method) { 
			if (method == "Draw") {
				return new Object[]{  };
			}
			if (method == "SyncBoxes") {
				return new Object[]{  };
			}
			return null;
		}
		// Methods from interface DrawInterface.
		public void draw(ServerCall call) throws VeyronException { 
			final ServerCall serverCall = call;
			final Stream<Box,Box> stream = new Stream<Box,Box>() {
				@Override
				public void send(Box item) throws VeyronException {
					serverCall.send(item);
				}
				@Override
				public Box recv() throws java.io.EOFException, VeyronException {
					final TypeToken<?> type = new TypeToken<Box>() {};
					final Object result = serverCall.recv(type);
					try {
						return (Box)result;
					} catch (java.lang.ClassCastException e) {
						throw new VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
					}
				}
			};
			this.service.draw(call, stream);
		}
		public void syncBoxes(ServerCall call) throws VeyronException { 
			this.service.syncBoxes(call);
		}
	}
}
