
// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;


/**
 * A GameID is used to uniquely identify a game within one Judge.
**/
public final class GameID { 
		private String iD;

	public GameID(String iD) { 
		this.iD = iD;
	}
	public String getID() { return this.iD; }

	public void setID(String iD) { this.iD = iD; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final GameID other = (GameID)obj;
		if (!(this.iD.equals(other.iD))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (iD == null ? 0 : iD.hashCode());
		return result;
	}
}
