
// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;


/**
 * GameOptions specifies the parameters of a game.
**/
public class GameOptions { 
	public int numRounds; // The number of rounds that a player must win to win the game.
	public byte gameType; // The type of game to play: Classic or LizardSpock.
}
