// This file was auto-generated by the veyron vdl tool.
// Source(s): wiretype.vdl
package com.veyron2.vom2;


public class VeyronConsts { 
	/* The following constants originate in file: wiretype.vdl. */
	// Primitives
	public static final TypeID WIRE_ANYID = new TypeID(1L);
		public static final TypeID WIRE_TYPEID = new TypeID(2L);
		public static final TypeID WIRE_BOOLID = new TypeID(3L);
		public static final TypeID WIRE_STRINGID = new TypeID(4L);
		public static final TypeID WIRE_BYTEID = new TypeID(5L);
		public static final TypeID WIRE_UINT16ID = new TypeID(6L);
		public static final TypeID WIRE_UINT32ID = new TypeID(7L);
		public static final TypeID WIRE_UINT64ID = new TypeID(8L);
		public static final TypeID WIRE_INT16ID = new TypeID(9L);
		public static final TypeID WIRE_INT32ID = new TypeID(10L);
		public static final TypeID WIRE_INT64ID = new TypeID(11L);
		public static final TypeID WIRE_FLOAT32ID = new TypeID(12L);
		public static final TypeID WIRE_FLOAT64ID = new TypeID(13L);
		public static final TypeID WIRE_COMPLEX64ID = new TypeID(14L);
		public static final TypeID WIRE_COMPLEX128ID = new TypeID(15L);
	// Composites only used in type definitions
	public static final TypeID WIRE_NAMEDID = new TypeID(16L);
		public static final TypeID WIRE_ENUMID = new TypeID(17L);
		public static final TypeID WIRE_ARRAYID = new TypeID(18L);
		public static final TypeID WIRE_LISTID = new TypeID(19L);
		public static final TypeID WIRE_SETID = new TypeID(20L);
		public static final TypeID WIRE_MAPID = new TypeID(21L);
		public static final TypeID WIRE_STRUCTID = new TypeID(22L);
		public static final TypeID WIRE_FIELDID = new TypeID(23L);
		public static final TypeID WIRE_FIELD_LISTID = new TypeID(24L);
		public static final TypeID WIRE_ONE_OFID = new TypeID(25L);
	// Other commonly used composites
	public static final TypeID WIRE_BYTE_LISTID = new TypeID(26L);
		public static final TypeID WIRE_STRING_LISTID = new TypeID(27L);
		public static final TypeID WIRE_TYPE_LISTID = new TypeID(28L);
	// The first user-defined TypeID is 65.  Note that -64 is encoded as 1 byte,
// while -65 is encoded as 2 bytes.
	public static final TypeID WIRE_TYPE_FIRST_USERID = new TypeID(65L);
}
