// This file was auto-generated by the veyron vdl tool.
// Source(s):  proximity.vdl
package com.veyron2.services.proximity;

import android.text.TextUtils;
import android.util.Log;

import com.google.common.reflect.TypeToken;
import com.veyron2.OptionDefs;
import com.veyron2.Options;
import com.veyron2.RuntimeFactory;
import com.veyron2.ipc.Context;
import com.veyron2.ipc.VeyronException;

import java.util.ArrayList;

public class Client { 
	/* Bind methods for interfaces in file: proximity.vdl. */
	public static ProximityAnnouncer bindProximityAnnouncer(String name) throws VeyronException {
		return bindProximityAnnouncer(name, null);
	}
	public static ProximityAnnouncer bindProximityAnnouncer(String name, Options opts) throws VeyronException {
		com.veyron2.ipc.Client client = null;
		if (opts != null && opts.get(OptionDefs.CLIENT) != null) {
			client = opts.get(OptionDefs.CLIENT, com.veyron2.ipc.Client.class);
		} else if (opts != null && opts.get(OptionDefs.RUNTIME) != null) {
			client = opts.get(OptionDefs.RUNTIME, com.veyron2.Runtime.class).getClient();
		} else {
			client = RuntimeFactory.getRuntime().getClient();
		}
		return new ProximityAnnouncerStub(client, name);
	}
	public static ProximityScanner bindProximityScanner(String name) throws VeyronException {
		return bindProximityScanner(name, null);
	}
	public static ProximityScanner bindProximityScanner(String name, Options opts) throws VeyronException {
		com.veyron2.ipc.Client client = null;
		if (opts != null && opts.get(OptionDefs.CLIENT) != null) {
			client = opts.get(OptionDefs.CLIENT, com.veyron2.ipc.Client.class);
		} else if (opts != null && opts.get(OptionDefs.RUNTIME) != null) {
			client = opts.get(OptionDefs.RUNTIME, com.veyron2.Runtime.class).getClient();
		} else {
			client = RuntimeFactory.getRuntime().getClient();
		}
		return new ProximityScannerStub(client, name);
	}
	public static Proximity bindProximity(String name) throws VeyronException {
		return bindProximity(name, null);
	}
	public static Proximity bindProximity(String name, Options opts) throws VeyronException {
		com.veyron2.ipc.Client client = null;
		if (opts != null && opts.get(OptionDefs.CLIENT) != null) {
			client = opts.get(OptionDefs.CLIENT, com.veyron2.ipc.Client.class);
		} else if (opts != null && opts.get(OptionDefs.RUNTIME) != null) {
			client = opts.get(OptionDefs.RUNTIME, com.veyron2.Runtime.class).getClient();
		} else {
			client = RuntimeFactory.getRuntime().getClient();
		}
		final ProximityAnnouncer proximityAnnouncer = Client.bindProximityAnnouncer(name, opts);
		final ProximityScanner proximityScanner = Client.bindProximityScanner(name, opts);
		return new ProximityStub(client, name, proximityAnnouncer, proximityScanner);
	}

	/* Client stubs for interfaces in file: proximity.vdl. */
	private static class ProximityAnnouncerStub implements ProximityAnnouncer {
		private static final String vdlIfacePathOpt = "com.veyron2.services.proximity.ProximityAnnouncer";
		private final com.veyron2.ipc.Client client;
		private final String name;

		ProximityAnnouncerStub(com.veyron2.ipc.Client client, String name) {
			this.client = client;
			this.name = name;
		}
		// Methods from interface ProximityAnnouncer.
		@Override
		public void registerName(Context context, String Name) throws VeyronException {
			registerName(context, Name, null);
		}
		@Override
		public void registerName(Context context, String Name, Options opts) throws VeyronException {
			// Prepare input arguments.
			final Object[] inArgs = new Object[]{ Name };

			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
			// Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityAnnouncerStub.vdlIfacePathOpt);
			}

			// Start the call.
			final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.name, "RegisterName", inArgs, opts);

			// Prepare output argument and finish the call.
			final TypeToken<?>[] resultTypes = new TypeToken<?>[]{  };
			call.finish(resultTypes);

		}
		@Override
		public void unregisterName(Context context, String Name) throws VeyronException {
			unregisterName(context, Name, null);
		}
		@Override
		public void unregisterName(Context context, String Name, Options opts) throws VeyronException {
			// Prepare input arguments.
			final Object[] inArgs = new Object[]{ Name };

			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
			// Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityAnnouncerStub.vdlIfacePathOpt);
			}

			// Start the call.
			final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.name, "UnregisterName", inArgs, opts);

			// Prepare output argument and finish the call.
			final TypeToken<?>[] resultTypes = new TypeToken<?>[]{  };
			call.finish(resultTypes);

		}
	}
	private static class ProximityScannerStub implements ProximityScanner {
		private static final String vdlIfacePathOpt = "com.veyron2.services.proximity.ProximityScanner";
		private final com.veyron2.ipc.Client client;
		private final String name;

		ProximityScannerStub(com.veyron2.ipc.Client client, String name) {
			this.client = client;
			this.name = name;
		}
		// Methods from interface ProximityScanner.
		@Override
		public ArrayList<Device> nearbyDevices(Context context) throws VeyronException {
			return nearbyDevices(context, null);
		}
		@Override
		public ArrayList<Device> nearbyDevices(Context context, Options opts) throws VeyronException {
			// Prepare input arguments.
			final Object[] inArgs = new Object[]{  };

			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
			// Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityScannerStub.vdlIfacePathOpt);
			}

			// Start the call.
			final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.name, "NearbyDevices", inArgs, opts);

			// Prepare output argument and finish the call.
			final TypeToken<?>[] resultTypes = new TypeToken<?>[]{ new TypeToken<ArrayList<Device>>() {} };
			Object[] results = call.finish(resultTypes);
			Log.v("Client", "Finish results [" + TextUtils.join(",  ", results) + "]");
			return (ArrayList<Device>)results[0];

		}
	}
	private static class ProximityStub implements Proximity {
		private static final String vdlIfacePathOpt = "com.veyron2.services.proximity.Proximity";
		private final com.veyron2.ipc.Client client;
		private final String name;
		private final ProximityAnnouncer proximityAnnouncer;
		private final ProximityScanner proximityScanner;

		ProximityStub(com.veyron2.ipc.Client client, String name, ProximityAnnouncer proximityAnnouncer, ProximityScanner proximityScanner) {
			this.client = client;
			this.name = name;
			this.proximityAnnouncer = proximityAnnouncer;
			this.proximityScanner = proximityScanner;
		}
		// Methods from sub-interface ProximityAnnouncer.
		@Override
		public void registerName(Context context, String Name) throws VeyronException {
			registerName(context, Name, null);
		}
		@Override
		public void registerName(Context context, String Name, Options opts) throws VeyronException {
			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
		    // Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityStub.vdlIfacePathOpt);
			}
			this.proximityAnnouncer.registerName(context, Name, opts);
		}
		@Override
		public void unregisterName(Context context, String Name) throws VeyronException {
			unregisterName(context, Name, null);
		}
		@Override
		public void unregisterName(Context context, String Name, Options opts) throws VeyronException {
			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
		    // Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityStub.vdlIfacePathOpt);
			}
			this.proximityAnnouncer.unregisterName(context, Name, opts);
		}
		// Methods from sub-interface ProximityScanner.
		@Override
		public ArrayList<Device> nearbyDevices(Context context) throws VeyronException {
			return nearbyDevices(context, null);
		}
		@Override
		public ArrayList<Device> nearbyDevices(Context context, Options opts) throws VeyronException {
			// Add VDL path option.
			// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
		    // Java to encoding/decoding from vom.Value objects.
			if (opts == null) opts = new Options();
			if (!opts.has(OptionDefs.VDL_INTERFACE_PATH)) {
				opts.set(OptionDefs.VDL_INTERFACE_PATH, ProximityStub.vdlIfacePathOpt);
			}
			return this.proximityScanner.nearbyDevices(context, opts);
		}
	}
}
