// This file was auto-generated by the veyron vdl tool.
// Source: proximity.vdl
package com.veyron2.services.proximity;


@com.veyron2.vdl.VeyronService(serviceWrapper=com.veyron2.services.proximity.gen_impl.ProximityScannerServiceWrapper.class)
public interface ProximityScannerService  {

    
    // NearbyDevices returns the most up-to-date list of nearby devices,
// sorted in increasing distance order.

    public java.util.ArrayList<com.veyron2.services.proximity.Device> nearbyDevices(final com.veyron2.ipc.ServerContext context) throws com.veyron2.ipc.VeyronException;

}
