// This file was auto-generated by the veyron vdl tool.
// Source: root.vdl
package com.veyron.services.mgmt.root;

/**
 * Root is an interface to be implemented by a process with root level
 * privileges.
 */

@com.veyron2.vdl.VeyronService(
	serviceWrapper = com.veyron.services.mgmt.root.gen_impl.RootServiceWrapper.class,
	vdlPathName = "veyron/services/mgmt/root/RootService"
)
public interface RootService  {

    
    // Reset waits for the given deadline (in milliseconds) and then
// restars the host node machine.

    public void reset(final com.veyron2.ipc.ServerContext context, final long Deadline) throws com.veyron2.ipc.VeyronException;

}
