
// This file was auto-generated by the veyron vdl tool.
// Source: tunnel.vdl
package com.veyron.examples.tunnel.vdlgen;

import java.util.ArrayList;

public class ShellOpts { 
	public boolean usePty; // Whether to open a pseudo-terminal
	public ArrayList<String> environment; // Environment variables to pass to the remote shell.
	public int rows; // Window size.
	public int cols;
}
