
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.security;


public class ACL2 { 
	public ACL value;

	public ACL2(ACL value) { 
		this.value = value;
	}
	public ACL getValue() { return this.value; }
	
	public void setValue(ACL value) { this.value = value; }
}
