
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.security;


/**
 * PrincipalPattern is a pattern identifying a set of principal names.
**/
public final class PrincipalPattern { 
		private String value;

	public PrincipalPattern(String value) { 
		this.value = value;
	}
	public String getValue() { return this.value; }

	public void setValue(String value) { this.value = value; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (!(obj instanceof PrincipalPattern)) return false;
		final PrincipalPattern other = (PrincipalPattern)obj;
		if (!(this.value.equals(other.value))) return false;
		return true;
	}
}
