// This file was auto-generated by the veyron vdl tool.
// Source(s): service.vdl
package com.veyron2.services.security.access;


public final class AccessConstants {
    

    /* The following constants originate in file: service.vdl */
    
    
    
    
    /**
 * The etag passed to SetACL is invalid.  Likely, another client set
 * the ACL already and invalidated the etag.  Use GetACL to fetch a
 * fresh etag.
 */

    public static final java.lang.String ERR_BAD_ETAG = "veyron2/services/security/access.ErrBadEtag";
    
    /**
 * The ACL is too big.  Use groups to represent large sets of principals.
 */

    public static final java.lang.String ERR_TOO_BIG = "veyron2/services/security/access.ErrTooBig";
    

    
}
