
// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package com.veyron.examples.storage.mdb.schema;


/**
 * Person represents a person, in any role, including producers, director,
 * actor, etc.
**/
public class Person { 
	public String image; // URL
	public String name;
	public long birthDate; // ns since the Unix epoch.
}
