
// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package com.veyron.examples.storage.mdb.schema;


/**
 * Review is a movie review.
**/
public final class Review { 
		private byte rating; // 1-10.
		private String text;

	public Review(byte rating, String text) { 
		this.rating = rating;
		this.text = text;
	}
	public byte getRating() { return this.rating; }
	public String getText() { return this.text; }

	public void setRating(byte rating) { this.rating = rating; }
	public void setText(String text) { this.text = text; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final Review other = (Review)obj;
		if (this.rating != other.rating) return false;
		if (!(this.text.equals(other.text))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (int)rating;
		result = prime * result + (text == null ? 0 : text.hashCode());
		return result;
	}
}
