// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;

/**
 * type GameOptions struct{NumRounds int32;GameType veyron/examples/rockpaperscissors.GameTypeTag byte} 
 * GameOptions specifies the parameters of a game.
 **/
public final class GameOptions implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      @com.google.gson.annotations.SerializedName("NumRounds")
      private int numRounds;
    
      @com.google.gson.annotations.SerializedName("GameType")
      private com.veyron.examples.rockpaperscissors.GameTypeTag gameType;
    

    
    public GameOptions(final int numRounds, final com.veyron.examples.rockpaperscissors.GameTypeTag gameType) {
        
            this.numRounds = numRounds;
        
            this.gameType = gameType;
        
    }

    
    
    public int getNumRounds() {
        return this.numRounds;
    }
    public void setNumRounds(int numRounds) {
        this.numRounds = numRounds;
    }
    
    public com.veyron.examples.rockpaperscissors.GameTypeTag getGameType() {
        return this.gameType;
    }
    public void setGameType(com.veyron.examples.rockpaperscissors.GameTypeTag gameType) {
        this.gameType = gameType;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final GameOptions other = (GameOptions)obj;

        
        
        
        if (this.numRounds != other.numRounds) {
            return false;
        }
         
         
        
        
        
        if (this.gameType == null) {
            if (other.gameType != null) {
                return false;
            }
        } else if (!this.gameType.equals(other.gameType)) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + numRounds;
        
        result = prime * result + (gameType == null ? 0 : gameType.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, numRounds);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, gameType);
    	
    }
	public static final android.os.Parcelable.Creator<GameOptions> CREATOR
		= new android.os.Parcelable.Creator<GameOptions>() {
		@Override
		public GameOptions createFromParcel(android.os.Parcel in) {
			return new GameOptions(in);
		}
		@Override
		public GameOptions[] newArray(int size) {
			return new GameOptions[size];
		}
	};
	private GameOptions(android.os.Parcel in) {
		
			this.numRounds = (int) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.numRounds);
		
			this.gameType = (com.veyron.examples.rockpaperscissors.GameTypeTag) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.gameType);
		
	}
}