// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;

/**
 * type JudgeAction struct{PlayerNum int32;OpponentName string;MoveOptions []string;RoundResult veyron/examples/rockpaperscissors.Round struct{Moves [2]string;Comment string;Winner veyron/examples/rockpaperscissors.WinnerTag byte;StartTimeNS int64;EndTimeNS int64};Score veyron/examples/rockpaperscissors.ScoreCard struct{Opts veyron/examples/rockpaperscissors.GameOptions struct{NumRounds int32;GameType veyron/examples/rockpaperscissors.GameTypeTag byte};Judge string;Players []string;Rounds []veyron/examples/rockpaperscissors.Round;StartTimeNS int64;EndTimeNS int64;Winner veyron/examples/rockpaperscissors.WinnerTag}} 
 **/
public final class JudgeAction implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      @com.google.gson.annotations.SerializedName("PlayerNum")
      private int playerNum;
    
      @com.google.gson.annotations.SerializedName("OpponentName")
      private java.lang.String opponentName;
    
      @com.google.gson.annotations.SerializedName("MoveOptions")
      private java.util.List<java.lang.String> moveOptions;
    
      @com.google.gson.annotations.SerializedName("RoundResult")
      private com.veyron.examples.rockpaperscissors.Round roundResult;
    
      @com.google.gson.annotations.SerializedName("Score")
      private com.veyron.examples.rockpaperscissors.ScoreCard score;
    

    
    public JudgeAction(final int playerNum, final java.lang.String opponentName, final java.util.List<java.lang.String> moveOptions, final com.veyron.examples.rockpaperscissors.Round roundResult, final com.veyron.examples.rockpaperscissors.ScoreCard score) {
        
            this.playerNum = playerNum;
        
            this.opponentName = opponentName;
        
            this.moveOptions = moveOptions;
        
            this.roundResult = roundResult;
        
            this.score = score;
        
    }

    
    
    public int getPlayerNum() {
        return this.playerNum;
    }
    public void setPlayerNum(int playerNum) {
        this.playerNum = playerNum;
    }
    
    public java.lang.String getOpponentName() {
        return this.opponentName;
    }
    public void setOpponentName(java.lang.String opponentName) {
        this.opponentName = opponentName;
    }
    
    public java.util.List<java.lang.String> getMoveOptions() {
        return this.moveOptions;
    }
    public void setMoveOptions(java.util.List<java.lang.String> moveOptions) {
        this.moveOptions = moveOptions;
    }
    
    public com.veyron.examples.rockpaperscissors.Round getRoundResult() {
        return this.roundResult;
    }
    public void setRoundResult(com.veyron.examples.rockpaperscissors.Round roundResult) {
        this.roundResult = roundResult;
    }
    
    public com.veyron.examples.rockpaperscissors.ScoreCard getScore() {
        return this.score;
    }
    public void setScore(com.veyron.examples.rockpaperscissors.ScoreCard score) {
        this.score = score;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final JudgeAction other = (JudgeAction)obj;

        
        
        
        if (this.playerNum != other.playerNum) {
            return false;
        }
         
         
        
        
        
        if (this.opponentName == null) {
            if (other.opponentName != null) {
                return false;
            }
        } else if (!this.opponentName.equals(other.opponentName)) {
            return false;
        }
         
         
        
        
        
        if (this.moveOptions == null) {
            if (other.moveOptions != null) {
                return false;
            }
        } else if (!this.moveOptions.equals(other.moveOptions)) {
            return false;
        }
         
         
        
        
        
        if (this.roundResult == null) {
            if (other.roundResult != null) {
                return false;
            }
        } else if (!this.roundResult.equals(other.roundResult)) {
            return false;
        }
         
         
        
        
        
        if (this.score == null) {
            if (other.score != null) {
                return false;
            }
        } else if (!this.score.equals(other.score)) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + playerNum;
        
        result = prime * result + (opponentName == null ? 0 : opponentName.hashCode());
        
        result = prime * result + (moveOptions == null ? 0 : moveOptions.hashCode());
        
        result = prime * result + (roundResult == null ? 0 : roundResult.hashCode());
        
        result = prime * result + (score == null ? 0 : score.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, playerNum);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, opponentName);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, moveOptions);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, roundResult);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, score);
    	
    }
	public static final android.os.Parcelable.Creator<JudgeAction> CREATOR
		= new android.os.Parcelable.Creator<JudgeAction>() {
		@Override
		public JudgeAction createFromParcel(android.os.Parcel in) {
			return new JudgeAction(in);
		}
		@Override
		public JudgeAction[] newArray(int size) {
			return new JudgeAction[size];
		}
	};
	private JudgeAction(android.os.Parcel in) {
		
			this.playerNum = (int) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.playerNum);
		
			this.opponentName = (java.lang.String) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.opponentName);
		
			this.moveOptions = (java.util.List<java.lang.String>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.moveOptions);
		
			this.roundResult = (com.veyron.examples.rockpaperscissors.Round) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.roundResult);
		
			this.score = (com.veyron.examples.rockpaperscissors.ScoreCard) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.score);
		
	}
}