// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;

/**
 * type PlayResult struct{YouWon bool} 
 * PlayResult is the value returned by the Play method. It indicates the outcome of the game.
 **/
public final class PlayResult {
    
    
      private boolean youWon;
    

    
    public PlayResult(final boolean youWon) {
        
            this.youWon = youWon;
        
    }

    
    
    public boolean getYouWon() {
        return this.youWon;
    }
    public void setYouWon(boolean youWon) {
        this.youWon = youWon;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final PlayResult other = (PlayResult)obj;

        
        
        if (this.youWon != other.youWon) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + java.lang.Boolean.valueOf(youWon).hashCode();
        
        return result;
    }
}