// This file was auto-generated by the veyron vdl tool.
// Source(s): service.vdl
package com.veyron.examples.rockpaperscissors;


public final class RockpaperscissorsConstants {
    

    /* The following constants originate in file: service.vdl */
    
    
    
    public static final com.veyron.examples.rockpaperscissors.GameTypeTag CLASSIC = new com.veyron.examples.rockpaperscissors.GameTypeTag((byte)0);
    
    
    public static final com.veyron.examples.rockpaperscissors.GameTypeTag LIZARD_SPOCK = new com.veyron.examples.rockpaperscissors.GameTypeTag((byte)1);
    
    
    public static final com.veyron.examples.rockpaperscissors.WinnerTag DRAW = new com.veyron.examples.rockpaperscissors.WinnerTag((byte)0);
    
    
    public static final com.veyron.examples.rockpaperscissors.WinnerTag PLAYER_1 = new com.veyron.examples.rockpaperscissors.WinnerTag((byte)1);
    
    
    public static final com.veyron.examples.rockpaperscissors.WinnerTag PLAYER_2 = new com.veyron.examples.rockpaperscissors.WinnerTag((byte)2);
    
    
    

    
}
