// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron.examples.rockpaperscissors;

/**
 * ScoreKeeper receives the outcome of games from Judges.
 */

public interface ScoreKeeper  {

    
    

    
    
    public void record(final com.veyron2.ipc.Context context, final com.veyron.examples.rockpaperscissors.ScoreCard Score) throws com.veyron2.ipc.VeyronException;
    public void record(final com.veyron2.ipc.Context context, final com.veyron.examples.rockpaperscissors.ScoreCard Score, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

}
