
// This file was auto-generated by the veyron vdl tool.
// Source: profile.vdl
package com.veyron.services.mgmt.profile;

import java.util.HashMap;

/**
 * Format includes a type (e.g. ELF) and each instance of the format
 * has some specific attributes. The key attributes are the target
 * operating system (e.g. for ELF this could be one of System V,
 * HP-UX, NetBSD, Linux, Solaris, AIX, IRIX, FreeBSD, and OpenBSD) and
 * the target instruction set architecture (e.g. for ELF this could be
 * one of SPARC, x86, PowerPC, ARM, IA-64, x86-64, and AArch64).
**/
public class Format { 
	public String name;
	public HashMap<String, String> attributes;
}
