// This file was auto-generated by the veyron vdl tool.
// Source: inspector.vdl
package com.veyron.examples.inspector;

/**
 * type Details struct{Name string;Size int64;Mode uint32;ModUnixSecs int64;ModNano int32;IsDir bool} 
 **/
public final class Details {
    
    
      private java.lang.String name;
    
      private long size;
    
      private int mode;
    
      private long modUnixSecs;
    
      private int modNano;
    
      private boolean isDir;
    

    
    public Details(final java.lang.String name, final long size, final int mode, final long modUnixSecs, final int modNano, final boolean isDir) {
        
            this.name = name;
        
            this.size = size;
        
            this.mode = mode;
        
            this.modUnixSecs = modUnixSecs;
        
            this.modNano = modNano;
        
            this.isDir = isDir;
        
    }

    
    
    public java.lang.String getName() {
        return this.name;
    }
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public long getSize() {
        return this.size;
    }
    public void setSize(long size) {
        this.size = size;
    }
    
    public int getMode() {
        return this.mode;
    }
    public void setMode(int mode) {
        this.mode = mode;
    }
    
    public long getModUnixSecs() {
        return this.modUnixSecs;
    }
    public void setModUnixSecs(long modUnixSecs) {
        this.modUnixSecs = modUnixSecs;
    }
    
    public int getModNano() {
        return this.modNano;
    }
    public void setModNano(int modNano) {
        this.modNano = modNano;
    }
    
    public boolean getIsDir() {
        return this.isDir;
    }
    public void setIsDir(boolean isDir) {
        this.isDir = isDir;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final Details other = (Details)obj;

        
        
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
         
        
        
        if (this.size != other.size) {
            return false;
        }
         
        
        
        if (this.mode != other.mode) {
            return false;
        }
         
        
        
        if (this.modUnixSecs != other.modUnixSecs) {
            return false;
        }
         
        
        
        if (this.modNano != other.modNano) {
            return false;
        }
         
        
        
        if (this.isDir != other.isDir) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (name == null ? 0 : name.hashCode());
        
        result = prime * result + java.lang.Long.valueOf(size).hashCode();
        
        result = prime * result + mode;
        
        result = prime * result + java.lang.Long.valueOf(modUnixSecs).hashCode();
        
        result = prime * result + modNano;
        
        result = prime * result + java.lang.Boolean.valueOf(isDir).hashCode();
        
        return result;
    }
}