// This file was auto-generated by the veyron vdl tool.
// Source(s):  service.vdl
package com.veyron.examples.rockpaperscissors.gen_impl;

import com.google.common.reflect.TypeToken;
import com.veyron.examples.rockpaperscissors.GameID;
import com.veyron.examples.rockpaperscissors.GameOptions;
import com.veyron.examples.rockpaperscissors.Judge;
import com.veyron.examples.rockpaperscissors.JudgeAction;
import com.veyron.examples.rockpaperscissors.JudgeFactory;
import com.veyron.examples.rockpaperscissors.JudgeService;
import com.veyron.examples.rockpaperscissors.PlayResult;
import com.veyron.examples.rockpaperscissors.Player;
import com.veyron.examples.rockpaperscissors.PlayerAction;
import com.veyron.examples.rockpaperscissors.PlayerFactory;
import com.veyron.examples.rockpaperscissors.PlayerService;
import com.veyron.examples.rockpaperscissors.RockPaperScissors;
import com.veyron.examples.rockpaperscissors.RockPaperScissorsFactory;
import com.veyron.examples.rockpaperscissors.RockPaperScissorsService;
import com.veyron.examples.rockpaperscissors.Round;
import com.veyron.examples.rockpaperscissors.ScoreCard;
import com.veyron.examples.rockpaperscissors.ScoreKeeper;
import com.veyron.examples.rockpaperscissors.ScoreKeeperFactory;
import com.veyron.examples.rockpaperscissors.ScoreKeeperService;
import com.veyron.examples.rockpaperscissors.VeyronConsts;
import com.veyron2.ipc.ServerCall;
import com.veyron2.ipc.VeyronException;
import com.veyron2.vdl.Stream;

public class JudgeServiceWrapper {

	private final JudgeService service;

	public JudgeServiceWrapper(JudgeService service) {
		this.service = service;
	}
	/**
	 * Returns all tags associated with the provided method or null if the method isn't implemented
	 * by this service.
	 */
	public Object[] getMethodTags(ServerCall call, String method) { 
		if ("createGame".equals(method)) {
			return new Object[]{  };
		}
		if ("play".equals(method)) {
			return new Object[]{  };
		}
		return null;
	}
	// Methods from interface Judge.
	public GameID createGame(ServerCall call, GameOptions Opts) throws VeyronException { 
		return this.service.createGame(call, Opts);
	}
	public PlayResult play(ServerCall call, GameID ID) throws VeyronException { 
		final ServerCall serverCall = call;
		final Stream<JudgeAction,PlayerAction> stream = new Stream<JudgeAction,PlayerAction>() {
			@Override
			public void send(JudgeAction item) throws VeyronException {
				serverCall.send(item);
			}
			@Override
			public PlayerAction recv() throws java.io.EOFException, VeyronException {
				final TypeToken<?> type = new TypeToken<PlayerAction>() {};
				final Object result = serverCall.recv(type);
				try {
					return (PlayerAction)result;
				} catch (java.lang.ClassCastException e) {
					throw new VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
				}
			}
		};
		return this.service.play(call, ID, stream);
	}
}
