// This file was auto-generated by the veyron vdl tool.
// Source: schema.vdl
package com.veyron.examples.todos.schema;

/**
 * type Dir struct{} 
 * Dir represents a directory.
 **/
public final class Dir {
    
    

    
    public Dir() {
        
    }

    
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final Dir other = (Dir)obj;

         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        return result;
    }
}