// This file was auto-generated by the veyron vdl tool.
// Source: tunnel.vdl
package com.veyron.examples.tunnel;

/**
 * type ServerShellPacket struct{Stdout []byte;Stderr []byte} 
 **/
public final class ServerShellPacket {
    
    
      private java.util.ArrayList<java.lang.Byte> stdout;
    
      private java.util.ArrayList<java.lang.Byte> stderr;
    

    
    public ServerShellPacket(final java.util.ArrayList<java.lang.Byte> stdout, final java.util.ArrayList<java.lang.Byte> stderr) {
        
            this.stdout = stdout;
        
            this.stderr = stderr;
        
    }

    
    
    public java.util.ArrayList<java.lang.Byte> getStdout() {
        return this.stdout;
    }
    public void setStdout(java.util.ArrayList<java.lang.Byte> stdout) {
        this.stdout = stdout;
    }
    
    public java.util.ArrayList<java.lang.Byte> getStderr() {
        return this.stderr;
    }
    public void setStderr(java.util.ArrayList<java.lang.Byte> stderr) {
        this.stderr = stderr;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final ServerShellPacket other = (ServerShellPacket)obj;

        
        
        if (this.stdout == null) {
            if (other.stdout != null) {
                return false;
            }
        } else if (!this.stdout.equals(other.stdout)) {
            return false;
        }
         
        
        
        if (this.stderr == null) {
            if (other.stderr != null) {
                return false;
            }
        } else if (!this.stderr.equals(other.stderr)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (stdout == null ? 0 : stdout.hashCode());
        
        result = prime * result + (stderr == null ? 0 : stderr.hashCode());
        
        return result;
    }
}