// This file was auto-generated by the veyron vdl tool.
// Source(s):  application.vdl
package com.veyron2.services.mgmt.application.vdlgen;

import com.veyron2.ipc.ServerCall;

public class Server { 
	/* Server stub creation methods for interfaces in file: application.vdl. */
	
	/* Server stubs for interfaces in file: application.vdl. */
}
