// This file was auto-generated by the veyron vdl tool.
// Source: exp.vdl
package com.veyron2.vdl.test_arith.exp;


public interface Exp  {

    
    

    
    
    public double exp(final com.veyron2.ipc.Context context, final double x) throws com.veyron2.ipc.VeyronException;
    public double exp(final com.veyron2.ipc.Context context, final double x, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

}
