
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.security;

/**
 * type BlessingPattern string 
 * BlessingPattern is a pattern that is matched by specific blessings.
 * 
 * A pattern can be either a blessing (slash-separated human-readable string)
 * or a blessing ending in a glob (""). A blessing matches a pattern if it
 * can be extended to produce the same string as the pattern.  For example, the
 * pattern "a/b/c" is matched by the blessings "a", "a/b" and "a/b/c" but not
 * "x", not "a/x", not "a/b/x" and not "a/b/c/x".
 * 
 * Additionally, when the pattern ends with a glob (""), it is matched by
 * all blessings that represent delegates of the pattern string excluding the
 * glob. For example, the pattern "a/b/c" is matched by all the patterns
 * that match "a/b/c" ("a", "a/b", "a/b/c") and all delegates of "a/b/c" (like
 * "a/b/c/d", "a/b/c/d/e" etc.).
 **/
public final class BlessingPattern {
    private java.lang.String value;

    public BlessingPattern(java.lang.String value) {
        this.value = value;
    }
    public java.lang.String getValue() { return this.value; }

    public void setValue(java.lang.String value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.security.BlessingPattern other = (com.veyron2.security.BlessingPattern)obj;
        
        if (this.value == null) {
            return other.value == null;
        }
        return this.value.equals(other.value);
        
    }
    @Override
    public int hashCode() {
        return (value == null ? 0 : value.hashCode());
    }
}
