// This file was auto-generated by the veyron vdl tool.
// Source(s):  root.vdl
package com.veyron.services.mgmt.root.gen_impl;

/* Client stub for interface: Root. */
public final class RootStub implements com.veyron.services.mgmt.root.Root {
    private static final java.lang.String vdlIfacePathOpt = "veyron/services/mgmt/root/Root";
    private final com.veyron2.ipc.Client client;
    private final java.lang.String veyronName;

    
    

    public RootStub(final com.veyron2.ipc.Client client, final java.lang.String veyronName) {
        this.client = client;
        this.veyronName = veyronName;
        
        
    }

    // Methods from interface Root.


    
    public void reset(final com.veyron2.ipc.Context context, final long Deadline) throws com.veyron2.ipc.VeyronException {
         reset(context, Deadline, null);
    }
    
    public void reset(final com.veyron2.ipc.Context context, final long Deadline, com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException {
        
        // Add VDL path option.
        // NOTE(spetrovic): this option is temporary and will be removed soon after we switch
        // Java to encoding/decoding from vom.Value objects.
        if (veyronOpts == null) veyronOpts = new com.veyron2.Options();
        if (!veyronOpts.has(com.veyron2.OptionDefs.VDL_INTERFACE_PATH)) {
            veyronOpts.set(com.veyron2.OptionDefs.VDL_INTERFACE_PATH, RootStub.vdlIfacePathOpt);
        }

        
        // Start the call.
        final java.lang.Object[] inArgs = new java.lang.Object[]{ Deadline };
        final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.veyronName, "reset", inArgs, veyronOpts);

        // Finish the call.
        
        

        
        final com.google.common.reflect.TypeToken<?>[] resultTypes = new com.google.common.reflect.TypeToken<?>[]{};
        call.finish(resultTypes);
         

        
    }





}
