// This file was auto-generated by the veyron vdl tool.
// Source(s):  root.vdl
package com.veyron.services.mgmt.root.vdlgen;

import com.veyron2.ipc.ServerCall;
import com.veyron2.ipc.VeyronException;

public class Server { 
	/* Server stub creation methods for interfaces in file: root.vdl. */
	public static Object newRoot(RootService service) { 
		return new RootStub(service);
	}
	
	/* Server stubs for interfaces in file: root.vdl. */
	public static class RootStub {
		private final RootService service;

		RootStub(RootService service) {
			this.service = service;
		}
		/**
		 * Returns all tags associated with the provided method or null if the method isn't implemented
		 * by this service.
		 */
		@SuppressWarnings("unused")
		public Object[] getMethodTags(ServerCall call, String method) { 
			if (method == "Reset") {
				return new Object[]{  };
			}
			return null;
		}
		// Methods from interface Root.
		public void reset(ServerCall call, long Deadline) throws VeyronException { 
			this.service.reset(call, Deadline);
		}
	}
}
