// This file was auto-generated by the veyron vdl tool.
// Source(s): logreader.vdl
package com.veyron2.services.mgmt.logreader;


public final class LogreaderConstants {
    

    /* The following constants originate in file: logreader.vdl */
    
    
    /**
 * A special NumEntries value that indicates that all entries should be
 * returned by ReadLog.
 */

    public static final long ALL_ENTRIES = -1L;
    
    
    

    
}
