// This file was auto-generated by the veyron vdl tool.
// Source(s):  node.vdl
package com.veyron.services.mgmt.node.gen_impl;

import com.veyron.services.mgmt.node.Config;
import com.veyron.services.mgmt.node.ConfigFactory;
import com.veyron.services.mgmt.node.ConfigService;
import com.veyron.services.mgmt.node.Node;
import com.veyron.services.mgmt.node.NodeFactory;
import com.veyron.services.mgmt.node.NodeService;
import com.veyron2.ipc.ServerCall;
import com.veyron2.ipc.VeyronException;

public class ConfigServiceWrapper {

	private final ConfigService service;

	public ConfigServiceWrapper(ConfigService service) {
		this.service = service;
	}
	/**
	 * Returns all tags associated with the provided method or null if the method isn't implemented
	 * by this service.
	 */
	public Object[] getMethodTags(ServerCall call, String method) { 
		if (method == "Set") {
			return new Object[]{  };
		}
		return null;
	}
	// Methods from interface Config.
	public void set(ServerCall call, String key, String value) throws VeyronException { 
		this.service.set(call, key, value);
	}
}
