// This file was auto-generated by the veyron vdl tool.
// Source: protocol.vdl
package com.veyron2.ipc;

/**
 * type Response struct{Error error struct{Id string;Msg string};EndStreamResults bool;NumPosResults uint64} 
 * Response describes the response header sent by the server to the client.  A
 * zero response header is sent before each streaming arg.  Thereafter a
 * non-zero response header is sent at the end of the RPC call, right before
 * the positional results.
 **/
public final class Response {
    
    
      private com.veyron2.ipc.VeyronException error;
    
      private boolean endStreamResults;
    
      private long numPosResults;
    

    
    public Response(final com.veyron2.ipc.VeyronException error, final boolean endStreamResults, final long numPosResults) {
        
            this.error = error;
        
            this.endStreamResults = endStreamResults;
        
            this.numPosResults = numPosResults;
        
    }

    
    
    public com.veyron2.ipc.VeyronException getError() {
        return this.error;
    }
    public void setError(com.veyron2.ipc.VeyronException error) {
        this.error = error;
    }
    
    public boolean getEndStreamResults() {
        return this.endStreamResults;
    }
    public void setEndStreamResults(boolean endStreamResults) {
        this.endStreamResults = endStreamResults;
    }
    
    public long getNumPosResults() {
        return this.numPosResults;
    }
    public void setNumPosResults(long numPosResults) {
        this.numPosResults = numPosResults;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final Response other = (Response)obj;

        
        
        if (this.error == null) {
            if (other.error != null) {
                return false;
            }
        } else if (!this.error.equals(other.error)) {
            return false;
        }
         
        
        
        if (this.endStreamResults != other.endStreamResults) {
            return false;
        }
         
        
        
        if (this.numPosResults != other.numPosResults) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (error == null ? 0 : error.hashCode());
        
        result = prime * result + java.lang.Boolean.valueOf(endStreamResults).hashCode();
        
        result = prime * result + java.lang.Long.valueOf(numPosResults).hashCode();
        
        return result;
    }
}