
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;

/**
 * type NamedFloat64 float64 
 **/
public final class NamedFloat64 implements android.os.Parcelable, java.io.Serializable, com.google.gson.TypeAdapterFactory {
    private double value;

    public NamedFloat64(double value) {
        this.value = value;
    }
    public double getValue() { return this.value; }

    public void setValue(double value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.vdl.test_base.NamedFloat64 other = (com.veyron2.vdl.test_base.NamedFloat64)obj;
        
        
        return this.value == other.value;
         
         
    }
    @Override
    public int hashCode() {
        return java.lang.Double.valueOf(value).hashCode();
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
   		com.veyron2.vdl.ParcelUtil.writeValue(out, value);
    }
	public static final android.os.Parcelable.Creator<NamedFloat64> CREATOR
		= new android.os.Parcelable.Creator<NamedFloat64>() {
		@Override
		public NamedFloat64 createFromParcel(android.os.Parcel in) {
			return new NamedFloat64(in);
		}
		@Override
		public NamedFloat64[] newArray(int size) {
			return new NamedFloat64[size];
		}
	};
	private NamedFloat64(android.os.Parcel in) {
		value = (double) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), value);
	}

	public NamedFloat64() {}

	@Override
	public <T> com.google.gson.TypeAdapter<T> create(com.google.gson.Gson gson, com.google.gson.reflect.TypeToken<T> type) {
		if (!type.equals(new com.google.gson.reflect.TypeToken<NamedFloat64>(){})) {
			return null;
		}
		final com.google.gson.TypeAdapter<java.lang.Double> delegate = gson.getAdapter(new com.google.gson.reflect.TypeToken<java.lang.Double>() {});
		return new com.google.gson.TypeAdapter<T>() {
			@Override
			public void write(com.google.gson.stream.JsonWriter out, T value) throws java.io.IOException {
				delegate.write(out, ((NamedFloat64) value).getValue());
			}
			@Override
			public T read(com.google.gson.stream.JsonReader in) throws java.io.IOException {
				return (T) new NamedFloat64(delegate.read(in));
			}
		};
	}
}
