
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;

/**
 * type NamedUint16 uint16 
 **/
public final class NamedUint16 {
    private short value;

    public NamedUint16(short value) {
        this.value = value;
    }
    public short getValue() { return this.value; }

    public void setValue(short value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.vdl.test_base.NamedUint16 other = (com.veyron2.vdl.test_base.NamedUint16)obj;
        
        return this.value == other.value;
        
    }
    @Override
    public int hashCode() {
        return (int)value;
    }
}
