
// This file was auto-generated by the veyron vdl tool.
// Source: base.vdl
package com.veyron2.vdl.test_base;

/**
 * type NamedBool bool 
 **/
public final class NamedBool implements android.os.Parcelable, java.io.Serializable, com.google.gson.TypeAdapterFactory {
    private boolean value;

    public NamedBool(boolean value) {
        this.value = value;
    }
    public boolean getValue() { return this.value; }

    public void setValue(boolean value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.vdl.test_base.NamedBool other = (com.veyron2.vdl.test_base.NamedBool)obj;
        
        
        return this.value == other.value;
         
         
    }
    @Override
    public int hashCode() {
        return java.lang.Boolean.valueOf(value).hashCode();
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
   		com.veyron2.vdl.ParcelUtil.writeValue(out, value);
    }
	public static final android.os.Parcelable.Creator<NamedBool> CREATOR
		= new android.os.Parcelable.Creator<NamedBool>() {
		@Override
		public NamedBool createFromParcel(android.os.Parcel in) {
			return new NamedBool(in);
		}
		@Override
		public NamedBool[] newArray(int size) {
			return new NamedBool[size];
		}
	};
	private NamedBool(android.os.Parcel in) {
		value = (boolean) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), value);
	}

	public NamedBool() {}

	@Override
	public <T> com.google.gson.TypeAdapter<T> create(com.google.gson.Gson gson, com.google.gson.reflect.TypeToken<T> type) {
		if (!type.equals(new com.google.gson.reflect.TypeToken<NamedBool>(){})) {
			return null;
		}
		final com.google.gson.TypeAdapter<java.lang.Boolean> delegate = gson.getAdapter(new com.google.gson.reflect.TypeToken<java.lang.Boolean>() {});
		return new com.google.gson.TypeAdapter<T>() {
			@Override
			public void write(com.google.gson.stream.JsonWriter out, T value) throws java.io.IOException {
				delegate.write(out, ((NamedBool) value).getValue());
			}
			@Override
			public T read(com.google.gson.stream.JsonReader in) throws java.io.IOException {
				return (T) new NamedBool(delegate.read(in));
			}
		};
	}
}
