// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.security.access;

/**
 * type ACL struct{In veyron2/services/security/access.Entries struct{Principals map[veyron2/security.BlessingPattern string]veyron2/security.LabelSet uint32;Groups map[veyron2/services/security/access.Group struct{Name string}]veyron2/security.LabelSet};NotIn veyron2/services/security/access.Entries} 
 * ACL (Access Control List) tracks which principals and groups have access to
 * an object and which principals and groups specifically do not have access
 * to an object.  For example:
 * ACL {
 * In {
 * Principals {
 * "user1": ["Read", "Write"],
 * "user2": ["Read"],
 * }
 * Groups {
 * Group{"google.com/engineering"}: ["Read"],
 * }
 * }
 * NotIn {
 * Principals {
 * "user1": ["Write"],
 * }
 * Groups {
 * Group{"google.com/eng-interns"}: ["Read", "Write", "Admin"],
 * }
 * }
 * }
 * NotIn subtracts privileges.  In this example, it says that "user1" has
 * only  "Read" access.  All of engineering has read access except for
 * engineering interns.
 * 
 * Principals can have multiple names.  As long as the principal has a name
 * that matches In and not NotIn, it is authorized. The reasoning is that the
 * principal can always hide a name if it wants to, so requiring all names to
 * satisfy the policy does not make sense.
 **/
public final class ACL {
    
    
      private com.veyron2.services.security.access.Entries in;
    
      private com.veyron2.services.security.access.Entries notIn;
    

    
    public ACL(final com.veyron2.services.security.access.Entries in, final com.veyron2.services.security.access.Entries notIn) {
        
            this.in = in;
        
            this.notIn = notIn;
        
    }

    
    
    public com.veyron2.services.security.access.Entries getIn() {
        return this.in;
    }
    public void setIn(com.veyron2.services.security.access.Entries in) {
        this.in = in;
    }
    
    public com.veyron2.services.security.access.Entries getNotIn() {
        return this.notIn;
    }
    public void setNotIn(com.veyron2.services.security.access.Entries notIn) {
        this.notIn = notIn;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final ACL other = (ACL)obj;

        
        
        if (this.in == null) {
            if (other.in != null) {
                return false;
            }
        } else if (!this.in.equals(other.in)) {
            return false;
        }
         
        
        
        if (this.notIn == null) {
            if (other.notIn != null) {
                return false;
            }
        } else if (!this.notIn.equals(other.notIn)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (in == null ? 0 : in.hashCode());
        
        result = prime * result + (notIn == null ? 0 : notIn.hashCode());
        
        return result;
    }
}
