// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl

/**
 * Package watch defines the types extending the release version of
 * the watch interface.
 */

package io.veyron.store.veyron2.services.watch;
