// This file was auto-generated by the veyron vdl tool.
// Source: appcycle.vdl
package com.veyron2.services.mgmt.appcycle.vdlgen;

import com.veyron2.ipc.ServerContext;
import com.veyron2.ipc.VeyronException;
import com.veyron2.vdl.Stream;

/**
 * AppCycle interfaces with the process running a veyron runtime.
**/
public interface AppCycleService { 
	// Stop initiates shutdown of the server.  It streams back periodic
// updates to give the client an idea of how the shutdown is
// progressing.
	public void stop(ServerContext context, Stream<Task,Void> stream) throws VeyronException;
	// ForceStop tells the server to shut down right away.  It can be issued
// while a Stop is outstanding if for example the client does not want
// to wait any longer.
	public void forceStop(ServerContext context) throws VeyronException;
}
