// This file was auto-generated by the veyron vdl tool.
// Source(s):  vsync.vdl
package io.veyron.store.veyron.runtimes.google.vsync.gen_impl;

/* Client stub for interface: Sync. */
public final class SyncStub implements io.veyron.store.veyron.runtimes.google.vsync.Sync {
    private static final java.lang.String vdlIfacePathOpt = "io.veyron.store.veyron.runtimes.google.vsync.Sync";
    private final com.veyron2.ipc.Client client;
    private final java.lang.String veyronName;

    
    

    public SyncStub(final com.veyron2.ipc.Client client, final java.lang.String veyronName) {
        this.client = client;
        this.veyronName = veyronName;
        
        
    }

    // Methods from interface Sync.


    
    public com.veyron2.vdl.ClientStream<java.lang.Void,io.veyron.store.veyron.runtimes.google.vsync.LogRec, io.veyron.store.veyron.runtimes.google.vsync.GenVector> getDeltas(final com.veyron2.ipc.Context context, final io.veyron.store.veyron.runtimes.google.vsync.GenVector In, final io.veyron.store.veyron.runtimes.google.vsync.DeviceID ClientID) throws com.veyron2.ipc.VeyronException {
        return getDeltas(context, In, ClientID, null);
    }
    
    public com.veyron2.vdl.ClientStream<java.lang.Void,io.veyron.store.veyron.runtimes.google.vsync.LogRec, io.veyron.store.veyron.runtimes.google.vsync.GenVector> getDeltas(final com.veyron2.ipc.Context context, final io.veyron.store.veyron.runtimes.google.vsync.GenVector In, final io.veyron.store.veyron.runtimes.google.vsync.DeviceID ClientID, com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException {
        
        // Add VDL path option.
        // NOTE(spetrovic): this option is temporary and will be removed soon after we switch
        // Java to encoding/decoding from vom.Value objects.
        if (veyronOpts == null) veyronOpts = new com.veyron2.Options();
        if (!veyronOpts.has(com.veyron2.OptionDefs.VDL_INTERFACE_PATH)) {
            veyronOpts.set(com.veyron2.OptionDefs.VDL_INTERFACE_PATH, SyncStub.vdlIfacePathOpt);
        }

        
        // Start the call.
        final java.lang.Object[] inArgs = new java.lang.Object[]{ In, ClientID };
        final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.veyronName, "getDeltas", inArgs, veyronOpts);

        // Finish the call.
        
         
        return new com.veyron2.vdl.ClientStream<java.lang.Void, io.veyron.store.veyron.runtimes.google.vsync.LogRec, io.veyron.store.veyron.runtimes.google.vsync.GenVector>() {
            @Override
            public void send(final java.lang.Void item) throws com.veyron2.ipc.VeyronException {
                call.send(item);
            }
            @Override
            public io.veyron.store.veyron.runtimes.google.vsync.LogRec recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
                final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken<io.veyron.store.veyron.runtimes.google.vsync.LogRec>() {
                    private static final long serialVersionUID = 1L;
                };
                final java.lang.Object result = call.recv(type);
                try {
                    return (io.veyron.store.veyron.runtimes.google.vsync.LogRec)result;
                } catch (java.lang.ClassCastException e) {
                    throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
                }
            }
            @Override
            public io.veyron.store.veyron.runtimes.google.vsync.GenVector finish() throws com.veyron2.ipc.VeyronException {
                 
                final com.google.common.reflect.TypeToken<?>[] resultTypes = new com.google.common.reflect.TypeToken<?>[]{
                    new com.google.common.reflect.TypeToken<io.veyron.store.veyron.runtimes.google.vsync.GenVector>() {
                        private static final long serialVersionUID = 1L;
                    }
                };
                return (io.veyron.store.veyron.runtimes.google.vsync.GenVector)call.finish(resultTypes)[0];
                 
            }
        };
        
    }





}
