#!/bin/bash

# Wrapper around the Go compiler that sets up the necessary
# environment variables for cross-compiling the veyron Go code for
# Android.

main() {
  export ARCH=android
  export GOOS=linux
  export GOARCH=arm
  export GOARM=7
  export ANDROID="${VEYRON_ROOT}/environment/android"
  export GOROOT="${ANDROID}/go"
  export CC="${ANDROID}/ndk-toolchain/bin/arm-linux-androideabi-gcc"
  export GOPATH="${GOPATH}:${VEYRON_ROOT}/veyron.new/go"

  local -r SCRIPT_DIR="${VEYRON_ROOT}/scripts/build"
  source "${SCRIPT_DIR}/go-common.sh"
  source "${SCRIPT_DIR}/go-bluetooth.sh"

  local -r JNI_WRAPPER="${VEYRON_ROOT}/environment/cout/jni-wrapper-1.0/${ARCH}"
  if [[ -d "${JNI_WRAPPER}" ]]; then
    export CGO_CFLAGS+=" -I${JNI_WRAPPER}/include"
    export CGO_LDFLAGS+=" -L${JNI_WRAPPER}/lib -Wl,-rpath ${JNI_WRAPPER}/lib"
  fi

  exec "${ANDROID}/go/bin/go" "$@"
}

main "$@"
