
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.storage;


/**
 * DEntry is a directory entry.
 */
public final class DEntry { 
		private String name;
		private ID iD;

	public DEntry(String name, ID iD) { 
		this.name = name;
		this.iD = iD;
	}
	public String getName() { return this.name; }
	public ID getID() { return this.iD; }

	public void setName(String name) { this.name = name; }
	public void setID(ID iD) { this.iD = iD; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final DEntry other = (DEntry)obj;
		if (!(this.name.equals(other.name))) return false;
		if (!(this.iD.equals(other.iD))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (name == null ? 0 : name.hashCode());
		result = prime * result + (iD == null ? 0 : iD.hashCode());
		return result;
	}
}
