// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package io.veyron.examples.rockpaperscissors;

/**
 * Player can receive challenges from other players.
 */

public interface Player  {

    
    

    
    // Challenge is used by other players to challenge this player to a game. If
// the challenge is accepted, the method returns nil.

    public void challenge(final com.veyron2.ipc.Context context, final java.lang.String Address, final io.veyron.examples.rockpaperscissors.GameID ID, final io.veyron.examples.rockpaperscissors.GameOptions Opts) throws com.veyron2.ipc.VeyronException;
    public void challenge(final com.veyron2.ipc.Context context, final java.lang.String Address, final io.veyron.examples.rockpaperscissors.GameID ID, final io.veyron.examples.rockpaperscissors.GameOptions Opts, final com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException;

}
