
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.query;


/**
 * Query is the Veyron query language.  The specification of this
 * language is at <placeholder>.
 */
public final class Query { 
	// Stmt is the human-readable representation of the query.
	private String stmt;

	public Query(String stmt) { 
		this.stmt = stmt;
	}
	public String getStmt() { return this.stmt; }

	public void setStmt(String stmt) { this.stmt = stmt; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final Query other = (Query)obj;
		if (!(this.stmt.equals(other.stmt))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (stmt == null ? 0 : stmt.hashCode());
		return result;
	}
}
