// This file was auto-generated by the veyron vdl tool.
// Source: inspector.vdl
package io.veyron.examples.inspector;


@com.veyron2.vdl.VeyronService(serviceWrapper=io.veyron.examples.inspector.gen_impl.InspectorServiceWrapper.class)
public interface InspectorService  {

    
    
    public void ls(final com.veyron2.ipc.ServerContext context, final java.lang.String Glob, com.veyron2.vdl.Stream<java.lang.Void, java.lang.String> stream) throws com.veyron2.ipc.VeyronException;

    
    
    public void lsDetails(final com.veyron2.ipc.ServerContext context, final java.lang.String Glob, com.veyron2.vdl.Stream<java.lang.Void, io.veyron.examples.inspector.Details> stream) throws com.veyron2.ipc.VeyronException;

}
