// This file was auto-generated by the veyron vdl tool.
// Source(s):  service.vdl
package io.veyron.examples.rockpaperscissors.gen_impl;

public final class ScoreKeeperServiceWrapper {

    private final io.veyron.examples.rockpaperscissors.ScoreKeeperService service;




    public ScoreKeeperServiceWrapper(final io.veyron.examples.rockpaperscissors.ScoreKeeperService service) {
        this.service = service;
        
        
    }

    /**
     * Returns all tags associated with the provided method or null if the method isn't implemented
     * by this service.
     */
    public java.lang.Object[] getMethodTags(final com.veyron2.ipc.ServerCall call, final java.lang.String method) throws com.veyron2.ipc.VeyronException {
        
        if ("getMethodTags".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("record".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        
        throw new com.veyron2.ipc.VeyronException("method: " + method + " not found");
    }

     
    
    public void record(final com.veyron2.ipc.ServerCall call, final io.veyron.examples.rockpaperscissors.ScoreCard Score) throws com.veyron2.ipc.VeyronException {
         
         this.service.record( call , Score  );
    }



 

}
