// This file was auto-generated by the veyron vdl tool.
// Source(s): service.vdl
package com.veyron2.services.store.vdlgen;


public class Consts { 
	/* The following constants originate in file: service.vdl. */
	// The Store has Veyron name "<mount>/.store", where <mount> is the
// Veyron name of the mount point.
// An Object with path <path> has Veyron name "<mount>/<path>".
public static final String STORE_SUFFIX = ".store";
}
