// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package io.veyron.store.veyron2.services.store;

/**
 * Dir is a directory containing Objects and other Dirs.
 */

public interface Dir extends io.veyron.store.veyron2.services.store.DirSpecific, io.veyron.store.veyron2.services.store.DirOrObject {

}
