// This file was auto-generated by the veyron vdl tool.
// Source: signature.vdl
package com.veyron2.ipc;

/**
 * type ServiceSignature struct{TypeDefs []any;Methods map[string]veyron2/ipc.MethodSignature struct{InArgs []veyron2/ipc.MethodArgument struct{Name string;Type veyron2/wiretype.TypeID uint64};OutArgs []veyron2/ipc.MethodArgument;InStream veyron2/wiretype.TypeID;OutStream veyron2/wiretype.TypeID}} 
 * ServiceSignature represents the signature of the service. This includes type information needed
 * to resolve the method argument types.
 * TODO(bprosnitz) Rename this and move it to wiretype.
 **/
public final class ServiceSignature implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      private java.util.List<com.veyron2.vdl.Any> typeDefs;
    
      private java.util.Map<java.lang.String, com.veyron2.ipc.MethodSignature> methods;
    

    
    public ServiceSignature(final java.util.List<com.veyron2.vdl.Any> typeDefs, final java.util.Map<java.lang.String, com.veyron2.ipc.MethodSignature> methods) {
        
            this.typeDefs = typeDefs;
        
            this.methods = methods;
        
    }

    
    
    public java.util.List<com.veyron2.vdl.Any> getTypeDefs() {
        return this.typeDefs;
    }
    public void setTypeDefs(java.util.List<com.veyron2.vdl.Any> typeDefs) {
        this.typeDefs = typeDefs;
    }
    
    public java.util.Map<java.lang.String, com.veyron2.ipc.MethodSignature> getMethods() {
        return this.methods;
    }
    public void setMethods(java.util.Map<java.lang.String, com.veyron2.ipc.MethodSignature> methods) {
        this.methods = methods;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final ServiceSignature other = (ServiceSignature)obj;

        
        
        if (this.typeDefs == null) {
            if (other.typeDefs != null) {
                return false;
            }
        } else if (!this.typeDefs.equals(other.typeDefs)) {
            return false;
        }
         
        
        
        if (this.methods == null) {
            if (other.methods != null) {
                return false;
            }
        } else if (!this.methods.equals(other.methods)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (typeDefs == null ? 0 : typeDefs.hashCode());
        
        result = prime * result + (methods == null ? 0 : methods.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, typeDefs);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, methods);
    	
    }
	public static final android.os.Parcelable.Creator<ServiceSignature> CREATOR
		= new android.os.Parcelable.Creator<ServiceSignature>() {
		@Override
		public ServiceSignature createFromParcel(android.os.Parcel in) {
			return new ServiceSignature(in);
		}
		@Override
		public ServiceSignature[] newArray(int size) {
			return new ServiceSignature[size];
		}
	};
	private ServiceSignature(android.os.Parcel in) {
		
			this.typeDefs = (java.util.List<com.veyron2.vdl.Any>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.typeDefs);
		
			this.methods = (java.util.Map<java.lang.String, com.veyron2.ipc.MethodSignature>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.methods);
		
	}
}