// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron.io.store.veyron2.storage;

/**
 * type Entry struct{Stat veyron.io/store/veyron2/storage.Stat struct{Kind veyron.io/store/veyron2/storage.Kind int16;ID veyron.io/store/veyron2/storage.ID [16]byte;MTimeNS int64;Attrs []any};Value any} 
 * Entry represents a value at some point in time in the store.
 **/
public final class Entry implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      @com.google.gson.annotations.SerializedName("Stat")
      private com.veyron.io.store.veyron2.storage.Stat stat;
    
      @com.google.gson.annotations.SerializedName("Value")
      private com.veyron2.vdl.Any value;
    

    
    public Entry(final com.veyron.io.store.veyron2.storage.Stat stat, final com.veyron2.vdl.Any value) {
        
            this.stat = stat;
        
            this.value = value;
        
    }

    
    
    public com.veyron.io.store.veyron2.storage.Stat getStat() {
        return this.stat;
    }
    public void setStat(com.veyron.io.store.veyron2.storage.Stat stat) {
        this.stat = stat;
    }
    
    public com.veyron2.vdl.Any getValue() {
        return this.value;
    }
    public void setValue(com.veyron2.vdl.Any value) {
        this.value = value;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final Entry other = (Entry)obj;

        
        
        
        if (this.stat == null) {
            if (other.stat != null) {
                return false;
            }
        } else if (!this.stat.equals(other.stat)) {
            return false;
        }
         
         
        
        
        
        if (this.value == null) {
            if (other.value != null) {
                return false;
            }
        } else if (!this.value.equals(other.value)) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (stat == null ? 0 : stat.hashCode());
        
        result = prime * result + (value == null ? 0 : value.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, stat);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, value);
    	
    }
	public static final android.os.Parcelable.Creator<Entry> CREATOR
		= new android.os.Parcelable.Creator<Entry>() {
		@Override
		public Entry createFromParcel(android.os.Parcel in) {
			return new Entry(in);
		}
		@Override
		public Entry[] newArray(int size) {
			return new Entry[size];
		}
	};
	private Entry(android.os.Parcel in) {
		
			this.stat = (com.veyron.io.store.veyron2.storage.Stat) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.stat);
		
			this.value = (com.veyron2.vdl.Any) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.value);
		
	}
}