// This file was auto-generated by the veyron vdl tool.
// Source(s): service.vdl
package io.veyron.store.veyron.services.store.raw;


public final class RawConstants {
    

    /* The following constants originate in file: service.vdl */
    
    
    /**
 * The raw Store has Object name "<mount>/.store.raw", where <mount> is the
 * Object name of the mount point.
 */

    public static final java.lang.String RAW_STORE_SUFFIX = ".store.raw";
    
    /**
 * NoVersion means the entry is not present in the store.
 */

    public static final io.veyron.store.veyron.services.store.raw.Version NO_VERSION = new io.veyron.store.veyron.services.store.raw.Version(0L);
    
    
    

    
}
