// This file was auto-generated by the veyron vdl tool.
// Source(s):  identity.vdl
package com.veyron.services.identity.gen_impl;

public final class OAuthBlesserServiceWrapper {

    private final com.veyron.services.identity.OAuthBlesserService service;




    public OAuthBlesserServiceWrapper(final com.veyron.services.identity.OAuthBlesserService service) {
        this.service = service;
        
        
    }

    /**
     * Returns all tags associated with the provided method or null if the method isn't implemented
     * by this service.
     */
    public java.lang.Object[] getMethodTags(final com.veyron2.ipc.ServerCall call, final java.lang.String method) throws com.veyron2.ipc.VeyronException {
        
        if ("blessUsingAccessToken".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("blessUsingAuthorizationCode".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("getMethodTags".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        
        throw new com.veyron2.ipc.VeyronException("method: " + method + " not found");
    }

     
    
    public java.lang.Object blessUsingAuthorizationCode(final com.veyron2.ipc.ServerCall call, final java.lang.String authcode, final java.lang.String redirecturl) throws com.veyron2.ipc.VeyronException {
         
         return  this.service.blessUsingAuthorizationCode( call , authcode, redirecturl  );
    }

    public java.lang.Object blessUsingAccessToken(final com.veyron2.ipc.ServerCall call, final java.lang.String token) throws com.veyron2.ipc.VeyronException {
         
         return  this.service.blessUsingAccessToken( call , token  );
    }



 

}
