// This file was auto-generated by the veyron vdl tool.
// Source: wiretype.vdl
package com.veyron2.wiretype;

/**
 * type NamedPrimitiveType struct{Type veyron2/wiretype.TypeID uint64;Name string;Tags []string} 
 * NamedPrimitiveType adds name and tag meta-information to a primitive type.
 **/
public final class NamedPrimitiveType implements android.os.Parcelable, java.io.Serializable {
    static final long serialVersionUID = 0L;

    
    
      private com.veyron2.wiretype.TypeID type;
    
      private java.lang.String name;
    
      private java.util.List<java.lang.String> tags;
    

    
    public NamedPrimitiveType(final com.veyron2.wiretype.TypeID type, final java.lang.String name, final java.util.List<java.lang.String> tags) {
        
            this.type = type;
        
            this.name = name;
        
            this.tags = tags;
        
    }

    
    
    public com.veyron2.wiretype.TypeID getType() {
        return this.type;
    }
    public void setType(com.veyron2.wiretype.TypeID type) {
        this.type = type;
    }
    
    public java.lang.String getName() {
        return this.name;
    }
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.util.List<java.lang.String> getTags() {
        return this.tags;
    }
    public void setTags(java.util.List<java.lang.String> tags) {
        this.tags = tags;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final NamedPrimitiveType other = (NamedPrimitiveType)obj;

        
        
        
        if (this.type == null) {
            if (other.type != null) {
                return false;
            }
        } else if (!this.type.equals(other.type)) {
            return false;
        }
         
         
        
        
        
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
         
         
        
        
        
        if (this.tags == null) {
            if (other.tags != null) {
                return false;
            }
        } else if (!this.tags.equals(other.tags)) {
            return false;
        }
         
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (type == null ? 0 : type.hashCode());
        
        result = prime * result + (name == null ? 0 : name.hashCode());
        
        result = prime * result + (tags == null ? 0 : tags.hashCode());
        
        return result;
    }
    @Override
    public int describeContents() {
    	return 0;
    }
    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, type);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, name);
    	
    		com.veyron2.vdl.ParcelUtil.writeValue(out, tags);
    	
    }
	public static final android.os.Parcelable.Creator<NamedPrimitiveType> CREATOR
		= new android.os.Parcelable.Creator<NamedPrimitiveType>() {
		@Override
		public NamedPrimitiveType createFromParcel(android.os.Parcel in) {
			return new NamedPrimitiveType(in);
		}
		@Override
		public NamedPrimitiveType[] newArray(int size) {
			return new NamedPrimitiveType[size];
		}
	};
	private NamedPrimitiveType(android.os.Parcel in) {
		
			this.type = (com.veyron2.wiretype.TypeID) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.type);
		
			this.name = (java.lang.String) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.name);
		
			this.tags = (java.util.List<java.lang.String>) com.veyron2.vdl.ParcelUtil.readValue(in, getClass().getClassLoader(), this.tags);
		
	}
}