// This file was auto-generated by the veyron vdl tool.
// Source: syncgroup.vdl
package com.veyron.services.syncgroup;

/**
 * type SyncGroupInfo struct{Name string;Config veyron/services/syncgroup.SyncGroupConfig struct{Desc string;PathPatterns []string;Options map[string]any;ACL veyron2/security.ACL struct{In veyron2/security.Entries struct{Principals map[veyron2/security.BlessingPattern string]veyron2/security.LabelSet uint32};NotIn veyron2/security.Entries};MountTables []string};RootOID veyron2/storage.ID [16]byte;ETag string;SGOID veyron/services/syncgroup.ID [16]byte;Joiners map[veyron/services/syncgroup.NameIdentity struct{Name string;Identity string}]veyron/services/syncgroup.JoinerMetaData struct{SyncPriority int32}} 
 * A SyncGroupInfo is the conceptual state of a SyncGroup object.
 **/
public final class SyncGroupInfo {
    
    
      private java.lang.String name;
    
      private com.veyron.services.syncgroup.SyncGroupConfig config;
    
      private com.veyron2.storage.ID rootOID;
    
      private java.lang.String eTag;
    
      private com.veyron.services.syncgroup.ID sGOID;
    
      private java.util.HashMap<com.veyron.services.syncgroup.NameIdentity, com.veyron.services.syncgroup.JoinerMetaData> joiners;
    

    
    public SyncGroupInfo(final java.lang.String name, final com.veyron.services.syncgroup.SyncGroupConfig config, final com.veyron2.storage.ID rootOID, final java.lang.String eTag, final com.veyron.services.syncgroup.ID sGOID, final java.util.HashMap<com.veyron.services.syncgroup.NameIdentity, com.veyron.services.syncgroup.JoinerMetaData> joiners) {
        
            this.name = name;
        
            this.config = config;
        
            this.rootOID = rootOID;
        
            this.eTag = eTag;
        
            this.sGOID = sGOID;
        
            this.joiners = joiners;
        
    }

    
    
    public java.lang.String getName() {
        return this.name;
    }
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public com.veyron.services.syncgroup.SyncGroupConfig getConfig() {
        return this.config;
    }
    public void setConfig(com.veyron.services.syncgroup.SyncGroupConfig config) {
        this.config = config;
    }
    
    public com.veyron2.storage.ID getRootOID() {
        return this.rootOID;
    }
    public void setRootOID(com.veyron2.storage.ID rootOID) {
        this.rootOID = rootOID;
    }
    
    public java.lang.String getETag() {
        return this.eTag;
    }
    public void setETag(java.lang.String eTag) {
        this.eTag = eTag;
    }
    
    public com.veyron.services.syncgroup.ID getSGOID() {
        return this.sGOID;
    }
    public void setSGOID(com.veyron.services.syncgroup.ID sGOID) {
        this.sGOID = sGOID;
    }
    
    public java.util.HashMap<com.veyron.services.syncgroup.NameIdentity, com.veyron.services.syncgroup.JoinerMetaData> getJoiners() {
        return this.joiners;
    }
    public void setJoiners(java.util.HashMap<com.veyron.services.syncgroup.NameIdentity, com.veyron.services.syncgroup.JoinerMetaData> joiners) {
        this.joiners = joiners;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final SyncGroupInfo other = (SyncGroupInfo)obj;

        
        
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
         
        
        
        if (this.config == null) {
            if (other.config != null) {
                return false;
            }
        } else if (!this.config.equals(other.config)) {
            return false;
        }
         
        
        
        if (this.rootOID == null) {
            if (other.rootOID != null) {
                return false;
            }
        } else if (!this.rootOID.equals(other.rootOID)) {
            return false;
        }
         
        
        
        if (this.eTag == null) {
            if (other.eTag != null) {
                return false;
            }
        } else if (!this.eTag.equals(other.eTag)) {
            return false;
        }
         
        
        
        if (this.sGOID == null) {
            if (other.sGOID != null) {
                return false;
            }
        } else if (!this.sGOID.equals(other.sGOID)) {
            return false;
        }
         
        
        
        if (this.joiners == null) {
            if (other.joiners != null) {
                return false;
            }
        } else if (!this.joiners.equals(other.joiners)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (name == null ? 0 : name.hashCode());
        
        result = prime * result + (config == null ? 0 : config.hashCode());
        
        result = prime * result + (rootOID == null ? 0 : rootOID.hashCode());
        
        result = prime * result + (eTag == null ? 0 : eTag.hashCode());
        
        result = prime * result + (sGOID == null ? 0 : sGOID.hashCode());
        
        result = prime * result + (joiners == null ? 0 : joiners.hashCode());
        
        return result;
    }
}