// This file was auto-generated by the veyron vdl tool.
// Source(s):  inspector.vdl
package com.veyron.examples.inspector.gen_impl;

import com.veyron.examples.inspector.Details;
import com.veyron.examples.inspector.Inspector;
import com.veyron.examples.inspector.InspectorFactory;
import com.veyron.examples.inspector.InspectorService;

/* Client stub for interface: Inspector. */
public final class InspectorStub implements Inspector {
	private static final java.lang.String vdlIfacePathOpt = "com.veyron.examples.inspector.Inspector";
	private final com.veyron2.ipc.Client client;
	private final java.lang.String name;

	public InspectorStub(com.veyron2.ipc.Client client, java.lang.String name) {
		this.client = client;
		this.name = name;
	}
	// Methods from interface Inspector.
	@Override
	public com.veyron2.vdl.ClientStream<java.lang.Void,java.lang.String,java.lang.Void> ls(com.veyron2.ipc.Context context, java.lang.String Glob) throws com.veyron2.ipc.VeyronException {
		return ls(context, Glob, null);
	}
	@Override
	public com.veyron2.vdl.ClientStream<java.lang.Void,java.lang.String,java.lang.Void> ls(com.veyron2.ipc.Context context, java.lang.String Glob, com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException {
		// Prepare input arguments.
		final java.lang.Object[] inArgs = new java.lang.Object[]{ Glob };

		// Add VDL path option.
		// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
		// Java to encoding/decoding from vom.Value objects.
		if (veyronOpts == null) veyronOpts = new com.veyron2.Options();
		if (!veyronOpts.has(com.veyron2.OptionDefs.VDL_INTERFACE_PATH)) {
			veyronOpts.set(com.veyron2.OptionDefs.VDL_INTERFACE_PATH, InspectorStub.vdlIfacePathOpt);
		}

		// Start the call.
		final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.name, "Ls", inArgs, veyronOpts);

		return new com.veyron2.vdl.ClientStream<java.lang.Void, java.lang.String, java.lang.Void>() {
			@Override
			public void send(java.lang.Void item) throws com.veyron2.ipc.VeyronException {
				call.send(item);
			}
			@Override
			public java.lang.String recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
				final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken<java.lang.String>() {};
				final java.lang.Object result = call.recv(type);
				try {
					return (java.lang.String)result;
				} catch (java.lang.ClassCastException e) {
					throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
				}
			}
			@Override
			public java.lang.Void finish() throws com.veyron2.ipc.VeyronException {
				// Prepare output argument and finish the call.
					final com.google.common.reflect.TypeToken<?>[] resultTypes = new com.google.common.reflect.TypeToken<?>[]{  };
					call.finish(resultTypes);
					return null;

			}
		};
	}
	@Override
	public com.veyron2.vdl.ClientStream<java.lang.Void,Details,java.lang.Void> lsDetails(com.veyron2.ipc.Context context, java.lang.String Glob) throws com.veyron2.ipc.VeyronException {
		return lsDetails(context, Glob, null);
	}
	@Override
	public com.veyron2.vdl.ClientStream<java.lang.Void,Details,java.lang.Void> lsDetails(com.veyron2.ipc.Context context, java.lang.String Glob, com.veyron2.Options veyronOpts) throws com.veyron2.ipc.VeyronException {
		// Prepare input arguments.
		final java.lang.Object[] inArgs = new java.lang.Object[]{ Glob };

		// Add VDL path option.
		// NOTE(spetrovic): this option is temporary and will be removed soon after we switch
		// Java to encoding/decoding from vom.Value objects.
		if (veyronOpts == null) veyronOpts = new com.veyron2.Options();
		if (!veyronOpts.has(com.veyron2.OptionDefs.VDL_INTERFACE_PATH)) {
			veyronOpts.set(com.veyron2.OptionDefs.VDL_INTERFACE_PATH, InspectorStub.vdlIfacePathOpt);
		}

		// Start the call.
		final com.veyron2.ipc.Client.Call call = this.client.startCall(context, this.name, "LsDetails", inArgs, veyronOpts);

		return new com.veyron2.vdl.ClientStream<java.lang.Void, Details, java.lang.Void>() {
			@Override
			public void send(java.lang.Void item) throws com.veyron2.ipc.VeyronException {
				call.send(item);
			}
			@Override
			public Details recv() throws java.io.EOFException, com.veyron2.ipc.VeyronException {
				final com.google.common.reflect.TypeToken<?> type = new com.google.common.reflect.TypeToken<Details>() {};
				final java.lang.Object result = call.recv(type);
				try {
					return (Details)result;
				} catch (java.lang.ClassCastException e) {
					throw new com.veyron2.ipc.VeyronException("Unexpected result type: " + result.getClass().getCanonicalName());
				}
			}
			@Override
			public java.lang.Void finish() throws com.veyron2.ipc.VeyronException {
				// Prepare output argument and finish the call.
					final com.google.common.reflect.TypeToken<?>[] resultTypes = new com.google.common.reflect.TypeToken<?>[]{  };
					call.finish(resultTypes);
					return null;

			}
		};
	}
}
