
// This file was auto-generated by the veyron vdl tool.
// Source: service.vdl
package com.veyron2.services.store;


/**
 * Entry represents a value at some point in time in the store.
**/
public class Entry { 
	// Stat is the entry's metadata.
public Stat stat;
	// Value is the value of the entry.
public java.lang.Object value;
}
