// This file was auto-generated by the veyron vdl tool.
// Source(s):  repository.vdl
package com.veyron2.services.mgmt.repository.gen_impl;

public final class ApplicationServiceWrapper {

    private final com.veyron2.services.mgmt.repository.ApplicationService service;




    public ApplicationServiceWrapper(final com.veyron2.services.mgmt.repository.ApplicationService service) {
        this.service = service;
        
        
    }

    /**
     * Returns all tags associated with the provided method or null if the method isn't implemented
     * by this service.
     */
    public java.lang.Object[] getMethodTags(final com.veyron2.ipc.ServerCall call, final java.lang.String method) throws com.veyron2.ipc.VeyronException {
        
        if ("getMethodTags".equals(method)) {
            return new java.lang.Object[] {
                
            };
        }
        
        if ("match".equals(method)) {
            return new java.lang.Object[] {
                 new com.veyron2.security.Label(1), 
            };
        }
        
        
        throw new com.veyron2.ipc.VeyronException("method: " + method + " not found");
    }

     
    
    public com.veyron2.services.mgmt.application.Envelope match(final com.veyron2.ipc.ServerCall call, final java.util.ArrayList<java.lang.String> Profiles) throws com.veyron2.ipc.VeyronException {
         
         return  this.service.match( call , Profiles  );
    }



 

}
