
// This file was auto-generated by the veyron vdl tool.
// Source: tunnel.vdl
package com.veyron.examples.tunnel;

import java.util.ArrayList;

public final class ServerShellPacket { 
	// Bytes coming from the shell's stdout.
	private ArrayList<Byte> stdout;
	// Bytes coming from the shell's stderr.
	private ArrayList<Byte> stderr;

	public ServerShellPacket(ArrayList<Byte> stdout, ArrayList<Byte> stderr) { 
		this.stdout = stdout;
		this.stderr = stderr;
	}
	public ArrayList<Byte> getStdout() { return this.stdout; }
	public ArrayList<Byte> getStderr() { return this.stderr; }

	public void setStdout(ArrayList<Byte> stdout) { this.stdout = stdout; }
	public void setStderr(ArrayList<Byte> stderr) { this.stderr = stderr; }

	@Override
	public boolean equals(java.lang.Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (this.getClass() != obj.getClass()) return false;
		final ServerShellPacket other = (ServerShellPacket)obj;
		if (!(this.stdout.equals(other.stdout))) return false;
		if (!(this.stderr.equals(other.stderr))) return false;
		return true;
	}
	@Override
	public int hashCode() {
		int result = 1;
		final int prime = 31;
		result = prime * result + (stdout == null ? 0 : stdout.hashCode());
		result = prime * result + (stderr == null ? 0 : stderr.hashCode());
		return result;
	}
}
