// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.storage;

/**
 * type ACL struct{Name string;Contents veyron2/security.ACL map[veyron2/security.PrincipalPattern string]veyron2/security.LabelSet uint32} 
 * ACL has a security.ACL and a name.
 **/
public final class ACL {
    
    
      private java.lang.String name;
    
      private com.veyron2.security.ACL contents;
    

    
    public ACL(final java.lang.String name, final com.veyron2.security.ACL contents) {
        
            this.name = name;
        
            this.contents = contents;
        
    }

    
    
    public java.lang.String getName() {
        return this.name;
    }
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public com.veyron2.security.ACL getContents() {
        return this.contents;
    }
    public void setContents(com.veyron2.security.ACL contents) {
        this.contents = contents;
    }
    

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final ACL other = (ACL)obj;

        
        
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
         
        
        
        if (this.contents == null) {
            if (other.contents != null) {
                return false;
            }
        } else if (!this.contents.equals(other.contents)) {
            return false;
        }
         
         
        return true;
    }
    @Override
    public int hashCode() {
        int result = 1;
        final int prime = 31;
        
        result = prime * result + (name == null ? 0 : name.hashCode());
        
        result = prime * result + (contents == null ? 0 : contents.hashCode());
        
        return result;
    }
}