
// This file was auto-generated by the veyron vdl tool.
// Source: types.vdl
package com.veyron2.storage;

/**
 * type Kind int16 
 * Kind makes it possible to tell the difference between Dirs and Objects.
 **/
public final class Kind {
    private short value;

    public Kind(short value) {
        this.value = value;
    }
    public short getValue() { return this.value; }

    public void setValue(short value) { this.value = value; }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (this.getClass() != obj.getClass()) return false;
        final com.veyron2.storage.Kind other = (com.veyron2.storage.Kind)obj;
        
        return this.value == other.value;
        
    }
    @Override
    public int hashCode() {
        return (int)value;
    }
}
