// This file was auto-generated by the veyron vdl tool.
// Source(s): types.vdl
package com.veyron2.storage;


public final class StorageConstants {
    

    /* The following constants originate in file: types.vdl */
    
    
    
    public static final com.veyron2.storage.Kind DIR_KIND = new com.veyron2.storage.Kind((short)0);
    
    
    public static final com.veyron2.storage.Kind OBJECT_KIND = new com.veyron2.storage.Kind((short)1);
    
    
    

    
}
