// This file was auto-generated by the veyron vdl tool.
// Source: p2b.vdl
package com.veyron.examples.pipetobrowser.vdlgen;

import com.veyron2.ipc.ServerContext;
import com.veyron2.ipc.VeyronException;
import com.veyron2.vdl.Stream;
import java.util.ArrayList;

/**
 * Viewer allows clients to stream data to it and to request a particular viewer to format and display the data.
**/
public interface ViewerService { 
	// Pipe creates a bidirectional pipe between client and viewer service, returns total number of bytes received by the service after streaming ends
	public long pipe(ServerContext context, Stream<Void,ArrayList<Byte>> stream) throws VeyronException;
}
